### ISSUE TITLE
Create a new account

### ISSUE THREAD

**Issue by controllinghand** [greymass/eos-voter#126]
This would be a great enhancement to this awesome wallet if you could add the ability to create a new account from scratch.

**Comment by javierjmc** [comment]
+1

**Comment by liondani** [comment]
Absolutely

**Comment by Another-Joe** [comment]
Include custom names?

**Comment by kargakis** [comment]
Yes, please

**Comment by aaroncox** [comment]
Available in 0.4.0+

![image](https://user-images.githubusercontent.com/677686/43350967-008307e2-91da-11e8-89bb-932272133f06.png)
