### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by fishcharlie** [greymass/eos-voter#1357]
### Platform

Desktop (MacOS)

### Description

Any chance Anchor could build a native Apple Silicon application so that Rosetta 2 isn't required to run?

**Comment by aaroncox** [comment]
Definitely something we can look into, I believe Electron natively supports building to it. 

I don't think this will happen for the 1.x release of Anchor desktop, but as we're building out the 2.x version I'll make sure its one of the release versions. I've added a line item to https://github.com/greymass/anchor-desktop/issues/1 for tracking purposes.
