### ISSUE TITLE
[iOS] Unable to load action data. Corrupt data at: Encountered unknown type:

### ISSUE THREAD

**Issue by jandrad** [greymass/eos-voter#1365]
### Description

When trying to sing an `atomicassets::createtmpl` action the application fails with this error.

![image](https://github.com/greymass/anchor/assets/227524/b9c811d1-d261-40e2-98ff-90e1ae327b2d)

### Platform

iOS

### Steps To Reproduce

This can be reproduced in the WAX testnet for example:

1. On iOS go to https://testnet.waxblock.io/account/atomicassets?action=createtempl#contract-actions
2. Enter the following data in the fields:
    * authorized_creator: alpacaworlds
    * collection_name: alpacaworlds
    * schema_name: test
    * transferable: true
    * burnable: true
    * max_supply: 0
    * immutable_data: [{"key":"name","value":["string","Test"]}]
3. Click submit transaction
4. Error will occur

### Contact Details

jose@neftyblocks.com

**Comment by aaroncox** [comment]
Thanks for the report, looks like an issue with the serializer in https://github.com/greymass/swift-eosio/ not understanding how to process the ABI for that action.

**Comment by jandrad** [comment]
> Thanks for the report, looks like an issue with the serializer in https://github.com/greymass/swift-eosio/ not understanding how to process the ABI for that action.

It seems this commit broke it https://github.com/greymass/swift-eosio/commit/a878b5a4b956ace0b5eaedd31c1d254cd7fcef92. In theory, the test -[EOSIOTests.ABICodableTests testComplexAbi] should cover this case and it is failing now.

**Comment by n13** [comment]
We had the same issue with our ABI
[dao.abi.json](https://github.com/greymass/anchor/files/14916989/dao.abi.json)

**Comment by aaroncox** [comment]
We released an update a couple days ago which I believe resolves this issue. Let us know if there are still actions/ABIs still experiencing this issue!

**Comment by jandrad** [comment]
> We released an update a couple days ago which I believe resolves this issue. Let us know if there are still actions/ABIs still experiencing this issue!

Thanks for the fix. I can confirm it is working correctly again!
