### ISSUE TITLE
New wallet resource issue - RAM / NET catch-22

### ISSUE THREAD

**Issue by tek-witch** [greymass/eos-voter#1377]
### Description

wallet: tekwitch.gm

- Can't purchase RAM (insufficient NET)
- Can't stake NET (insufficient RAM)
- NET does not replenish

Tried allocating resources via Anchor wallet desktop app (windows), as well as waxblock.io.  Same result via both interfaces.

### Platform

Desktop (windows 10)

### Steps To Reproduce

Unclear if this is replicable across wallets, but resource allocation has been broken on this wallet since I purchased it.

### Contact Details

perpetrator@tekwitch.com

### Anything else?

![image](https://github.com/greymass/anchor/assets/11589980/92c5275d-4dec-49f6-9731-676578a5f8e2)

![image](https://github.com/greymass/anchor/assets/11589980/0ce0bb2d-2f4c-43b5-a2b7-381ea216a4a1)

**Comment by aaroncox** [comment]
The NET resource (as well as CPU) should be getting applied automatically, allowing the RAM purchase. 

I checked our server logs from the resource providing service, and it looks like the RAM purchase transaction was actually invalid. Maybe there was an insufficient balance to purchase the RAM, or the quantity of bytes was too low? 

I'd try the RAM purchase again with a different amount and ensure theres enough of a balance to purchase it.

The error messages here seem to be the biggest problem, since it's not surfacing the actual error during the RAM purchase 🤔

**Comment by tek-witch** [comment]
Thanks for looking into this with me.  The error messages are a bit short on detail. :)

> I'd try the RAM purchase again with a different amount and ensure theres enough of a balance to purchase it.

Retrying:

![image](https://github.com/greymass/anchor/assets/11589980/f284bce7-5870-415b-b3ec-4a5047a47701)
![image](https://github.com/greymass/anchor/assets/11589980/556c484a-e779-469d-a90e-a899e1bb67f8)

![image](https://github.com/greymass/anchor/assets/11589980/55a93230-1c96-44b8-98aa-f3f2c7bfbeb5)
![image](https://github.com/greymass/anchor/assets/11589980/baa311e6-0098-4bc1-b2d3-7f12b4d86cb7)

![image](https://github.com/greymass/anchor/assets/11589980/4ba9b9cd-62f7-49f6-bedd-7693af80a963)
![image](https://github.com/greymass/anchor/assets/11589980/9225df03-f8db-4cbc-aca0-992dc5d546d4)

Let me know if there's something else I can do on my end to help.

**Comment by aaroncox** [comment]
Thanks, that helped at least narrow it down. I think I found the issue on our end as to why CPU/NET weren't being applied for WAX (one of the APIs wasn't responding properly). 

Give it a try again with the amount you were looking for, and let me know if it works!

**Comment by tek-witch** [comment]
Success!  Looks like you have it sorted out.  Thank you kindly for the assist.

![image](https://github.com/greymass/anchor/assets/11589980/1a2bf71d-f04a-4a3e-b332-ca1603bc8aba)

**Comment by aaroncox** [comment]
Not a problem, thanks for reporting the issue!
