### ISSUE TITLE
Upgrade Available Button

### ISSUE THREAD

**Issue by controllinghand** [greymass/eos-voter#142]
Can you add to the wallet when a new version is available for download?

If you have time can you also make it so when you push the upgrade button it auto downloads and installs?  That might be asking to much?

Thanks again.

**Comment by aaroncox** [comment]
We have the "Help > Check for Updates" button in the menu bar as a first step, which when triggered, does check for updates and will allow you to automatically download new releases.

However, a design decision we made when starting this project was that the wallet itself would never connect to any server unless the user specifically asked it to (for security reasons). Having it automatically check and notify of updates goes against this design. 

While it would be useful to automatically notify the user of upgrades, I'm not sure if we want to change our stance on this philosophy at this time.

**Comment by controllinghand** [comment]
All great points!  And I agree with that direction.  If you want you can remove this thread.
