### ISSUE TITLE
Unable to Send Custom Tokens when 0 EOS (liquid) Balance

### ISSUE THREAD

**Issue by insalaco** [greymass/eos-voter#143]
I have EOS staked but the liquid EOS is 0. 
I am unable to send custom tokens because send interface is missing. see attached

<img width="1280" alt="image 2018-06-25 at 4 21 05 pm" src="https://user-images.githubusercontent.com/934208/41873930-70912dac-7894-11e8-8aa8-9c0f2d823b78.png">

**Comment by aaroncox** [comment]
Hrm those tools should be there regardless of your balance. 

We have seen a couple people end up in this weird state with the most recent upgrade. We are investigating what is causing it, but to immediately fix the problem you can click on the logo up in the upper right, scroll to the bottom, and delete your local wallet. You will have to setup your account again (and import the key once more), but your wallet should be immediately available for actions at that point.
