### ISSUE TITLE
Error when voting for BP using v2.1.0

### ISSUE THREAD

**Issue by TAMustafa** [greymass/eos-voter#146]
After pressing "Submit for Voting" Button the following message appears.
TypeError:  This Transaction requires a config.keyProvider for signing.

![screen shot 2018-06-26 at 07 21 49](https://user-images.githubusercontent.com/18684763/41890830-ab81a842-7911-11e8-829a-48e208a91fff.png)

**Comment by ScottSallinen** [comment]
Check to see if your wallet is unlocked: in the top right, is the icon green and locked? If so, click it, enter your wallet encryption password, and try again.

**Comment by TAMustafa** [comment]
Yes that worked. Thank you.

**Comment by aaroncox** [comment]
This is resolved and more clear in the 0.2.2 release (coming soon).
