### ISSUE TITLE
Public key lookup failed

### ISSUE THREAD

**Issue by wjmelements** [greymass/eos-voter#152]
On current master (18d3c4db69221d8b59fd7b6f7f8aedcb9b138472) I enter my public key (EOS71WWpUE3Y4uPkeUbbLhndKqooTqdGkz9Ay8AoMEPkyaJGRSbnJ) on step two of account setup and it doesn't find the account, but when I entered the account (gy2tgnzvhege) it was found. Perhaps I had extra whitespace or a period at the end of my paste that was ruining the lookup; some formatting checks may be the fix if public key lookup isn't actually broken.

**Comment by aaroncox** [comment]
This has been fixed in 0.2.2 which is now available.
