### ISSUE TITLE
Desktop Launcher bug

### ISSUE THREAD

**Issue by StevenAbaby** [greymass/eos-voter#155]
I'm running Linux Mint 18.2.  See results of a terminal copy below:

steve@steve-Inspiron-5721 ~/Downloads/eos voter 0.2.1/bin $ pwd
/home/steve/Downloads/eos voter 0.2.1/bin
steve@steve-Inspiron-5721 ~/Downloads/eos voter 0.2.1/bin $ ls -l
total 28
-rwxr-xr-x 1 steve steve 16432 May 21 00:17 desktop-launch
steve@steve-Inspiron-5721 ~/Downloads/eos voter 0.2.1/bin $ ./desktop-launch 
mkdir: cannot create directory ‘/.local’: Permission denied
mkdir: cannot create directory ‘/.cache’: Permission denied
mkdir: cannot create directory ‘/.config’: Permission denied
cp: '/home/steve/.config/user-dirs.locale' and '/home/steve/.config/user-dirs.locale' are the same file
mkdir: cannot create directory '/.config': Permission denied
ln: failed to create symbolic link '/.config/dconf': No such file or directory
mkdir: cannot create directory '/.config': Permission denied
ln: failed to create symbolic link '/.config/gtk-3.0/settings.ini': No such file or directory
mkdir: cannot create directory '/.config': Permission denied
ln: failed to create symbolic link '/.config/gtk-3.0/bookmarks': No such file or directory
mkdir: cannot create directory '/.config': Permission denied
ln: failed to create symbolic link '/.config/gtk-2.0/gtkfilechooser.ini': No such file or directory
mkdir: cannot create directory '/.config': Permission denied
ln: failed to create symbolic link '/.config/ibus': No such file or directory
./desktop-launch: line 435: /flavor-select: No such file or directory
steve@steve-Inspiron-5721 ~/Downloads/eos voter 0.2.1/bin $

**Comment by aaroncox** [comment]
I know this issue is old - but from the sounds of it, the user didn't have permissions to create those folders. `sudo` probably would have given it the permissions required, or `chmod`/`chown` the folder it's in.
