### ISSUE TITLE
Give the ability to bid on EOS premium names (Name Action)

### ISSUE THREAD

**Issue by liondani** [greymass/eos-voter#162]
![bid_name](https://user-images.githubusercontent.com/6908400/41973933-2ba82466-7a1f-11e8-959f-9e199585e67a.jpeg)

It would be fantastic to let your userbase bid on premium names. It would give much value to EOS to give the oportunity to MORE users to bid on names. I am sure many that would not vote will do if they find it easy from a allready installed wallet.

**Comment by aaroncox** [comment]
Tentatively slating this for the `0.6.x` milestone, couple versions out still. There's been an incredible demand for account creation and account permissions, which will be the two builds between now and then.

**Comment by dafuga** [comment]
This feature has been live for a while now.
