### ISSUE TITLE
CAN'T PASTE PUBLIC OR PRIVATE KEY INTO DIALOGUE BOX

### ISSUE THREAD

**Issue by pjbnikao** [greymass/eos-voter#163]
HOW COME. THIS STUPID FRIGGEN JOKE%####

**Comment by aaroncox** [comment]
Press CTRL+V, you can paste.

**Comment by pjbnikao** [comment]
THX.I am in the habit of just clicking with the mouse.

**Comment by pjbnikao** [comment]
Please forward to the appropriate party. This needs to be fixed. I am just
not in the habit of using Control - V to paste a document. I am so much not
in the habit of doing that it didn't even occur to me do that. IN FACT, I
EVEN RECALL READING ABOUT SOMEONE WHO HAD TO ENTER HIS KEYS MANUALLY.... so
maybe I am not the only person in town who has had this problem. SO YOU
NEED TO GET THIS FIXED BECAUSE I HAVE LITERALLY LOST HOURS OF MY TIME ON
THIS ONE TINY LITTLE DETAIL. ONE THING I'VE DISCOVERED IS THAT THERE A LOT
OF FRUSTRATED PEOPLE OVER AT TELEGRAM VOICING THEIR FRUSTRATION ABOUT THE
COMPLEXITY OF THIS ENTIRE PROCESS. IT'S BEEN 27 DAYS SINCE THE LAUNCH AND I
STILL CAN'T LOCATE MY ACCOUNT ON  EOSSPHERE.😡
