### ISSUE TITLE
When trying to vote while wallet is locked 

### ISSUE THREAD

**Issue by bitcoiners** [greymass/eos-voter#165]
Message should be more clear than 

![image](https://user-images.githubusercontent.com/38520/42015233-afe02ac4-7ad0-11e8-963e-e72662d16b28.png)

**Comment by ScottSallinen** [comment]
You should not be able to vote if your wallet is locked as of 0.2.2. Are you experiencing this issue in the latest version?

**Comment by bitcoiners** [comment]
No, this is on 0.2.1

**Comment by aaroncox** [comment]
0.2.2 fixes this.
