### ISSUE TITLE
Let's Talk Backup and Recovery

### ISSUE THREAD

**Issue by controllinghand** [greymass/eos-voter#166]
As you start to add more and more features to this awesome application we need a way to backup and recover.  I know, right now you only support one pub/priv key but once you start supporting multiple accounts we will need a way to export said pub and priv keys.  Also, if you ever add the feature to create an account from scratch this will be a must.

It can start out as a simple export to a cvs file.

Thanks!

**Comment by aaroncox** [comment]
I think to start with, we'll probably offer a JSON export, in both an encrypted and decrypted fashion. 

This feature will probably be a future release, after we get multi accounts implemented.

**Comment by controllinghand** [comment]
Perfect! Look forward to the update.

**Comment by aaroncox** [comment]
Still on our radar, but haven't made progress on it. Bumping off to 0.6.0.

**Comment by controllinghand** [comment]
Understand.  By the way I love all the new features.  Especially the smart contract interface.  Wow!

**Comment by aaroncox** [comment]
Closing this one out, we've got backup/restore features now in any version 0.6.5+.
