### ISSUE TITLE
CAN'T UNLOCK MY WALLET

### ISSUE THREAD

**Issue by pjbnikao** [greymass/eos-voter#170]
I am unable to unlock my wallet. I am very clear about the password I entered. I entered it two times as required and saved it even though you have no mechanism that allows me to visually verify it like on MEW. THIS IS REALLY STUPID.  I have now tried to unlock my wallet, but it will not open.  What needs to happen so I can gain access to my private key and public keys.  pjbnikao7@gmail.com

**Comment by aaroncox** [comment]
If you don’t have the correct password, the only way to use the wallet then is to reset the local wallet and reimport the keys again. You can destroy the local wallet by clicking on the logo in the upper right, and there’s a red button on the bottom of that screen for destroying the local wallet. After it’s removed, you’ll be able to go through the setup process again and reimport your account and private keys. 

There is no way to retrieve the private keys from a wallet if you don’t have the password.

**Comment by pjbnikao** [comment]
Aaron... Once again... a million thanks!!!

**Comment by pjbnikao** [comment]
Aaron

It's Phil again. I have destroyed the wallet and attempted to initiate the
process again. When I pasted the *account name* which I received from
eosauthority.com or the* public address* which gives me the data on my
account, I am informed that the account cannot be located. This same public
address when pasted into etherscan.io, esopark.io or eosflare.io gives me
all the same data that I find at eosauthority.com yet they are all unable
to give the location of the account. However, on one occasion I did enter
in the public address into the greymass wallet and it connected so I could
set up the wallet. Unfortunately, after that, I had problems entering the
correct private key. Has anyone else had this problem and what do you
recommend I do?

Appreciate your assistance.

Thx

Phil
