### ISSUE TITLE
Sent tokens to exchange 20 minutes not showing

### ISSUE THREAD

**Issue by stevej1234** [greymass/eos-voter#171]
Hi greymass, sent tokens to exchange. Not showing after 20 minutes. Please advise.

https://eostracker.io/transactions/b17d7d08dc31a8834196b9dc8e1ecc184c7c13fc8e5c6f41cd3117392fe80882

Thanks...

**Comment by aaroncox** [comment]
From the looks of the transaction, it successfully left your wallet and went to kraken. If it's not showing there, contact their support. There's nothing we can do from our side.
