### ISSUE TITLE
I can't change my account in the wallet

### ISSUE THREAD

**Issue by Gutalean** [greymass/eos-voter#173]
When I start the wallet the authentication screen pops up and disappears really quickly. I just haven't enough time to do something with it. And after that I don't know how to go back to that screen. All I have are: producers voting, wallet and tools. But none of it enables me to change my account.

**Comment by aaroncox** [comment]
There's no easy way to switch yet, currently it requires using the "Destroy Local Wallet" action to remove the old account and let you import a new one. We are working on multi account features right now and will have a release featuring it sometime this upcoming week.

**Comment by aaroncox** [comment]
Multiple accounts is now supported in 0.3.0.
