### ISSUE TITLE
Give ability to set a proxy with the cold wallet / watch wallet

### ISSUE THREAD

**Issue by plouto5** [greymass/eos-voter#174]
It would be a huge positive to people who never want there main accounts keys to touch the internet. It would make it possible to allow us to vote with these wallets. Thank you

**Comment by aaroncox** [comment]
It's on our short list and I imagine we'll see being able to set a proxy in one of the upcoming versions.

**Comment by plouto5** [comment]
Awesome looking forward to it thank you!

**Comment by plouto5** [comment]
Added to 0.3.0 Thanks so much!
