### ISSUE TITLE
Signing error

### ISSUE THREAD

**Issue by JohnAlf** [greymass/eos-voter#175]
I put some votes together yesterday and was called away before I could sign. It expired. Today I began again, created the JSON file, transferred it to my airgapped computer, imported it and got the error you see in this picture. As you can see, the file is only 8 minutes old, yet it says it is expired. It would not let me sign it. 
![img_1149](https://user-images.githubusercontent.com/40725765/42129701-9bffdfec-7c9a-11e8-8449-63e06de3b5de.jpg)
Something hung up from the file the day before?

**Comment by JohnAlf** [comment]
aaroncox, thanks for your speedy response. I checked the date/time. They are valid. Ran it again with a new file (deleting the old from the thumbdrive). Same problem. Seems to be hung-up because I let the first one expire, unsigned.

**Comment by aaroncox** [comment]
I'll look into what harm would come from removing that check on the cold wallet setup, and allow the signing of transactions even if it doesn't believe it's within the proper timeframe. I'll see if we can slate that for a `0.3.x` release here soon.
