### ISSUE TITLE
Wallet reports insufficient RAM

### ISSUE THREAD

**Issue by Mustard5** [greymass/eos-voter#177]
I don't know whether this is a reality of using EOS or a bug in the wallet.

I created a second account name a few days after the main net came online.  Today I decided to toy around with making a transfer of tokens to the other account and then unstaking a small portion of of cpu and network stake.

I successfully made a transfer of 0.0001 EOS to another account.  I then attempted to unstake a 5% portion of my CPU and NETWORK stake.  The wallet reported that I had insufficient RAM for the task.

Does this sound like a wallet bug or a limitation of EOS?

I can't wrap my head around not being able to take two actions on my account without running out of RAM.

![rameos](https://user-images.githubusercontent.com/378530/42164410-f09ed866-7dd3-11e8-92a4-0118910aecbc.PNG)

**Comment by andybets** [comment]
I think this might actually an EOS issue rather than one with the wallet.

**Comment by Mustard5** [comment]
I do have a number of dust bids in the name bidding process.  I don't know if that is relevant or not.

**Comment by aaroncox** [comment]
Yeah this seems like an EOS issue itself. We aren't really preventing you from doing anything based on the amount of RAM in your account - any error returned is coming from EOS itself and not the wallet. 

I'll bet it's those name bids that are occupying your RAM currently. I haven't done any name bidding, but I do have an account with a couple dozen transactions, and it's still sitting at 3.4kb of RAM used.

**Comment by aaroncox** [comment]
Going to close this - but will be interested in looking deeper into what actually consumes the most RAM for accounts.
