### ISSUE TITLE
'not have signatures' Error

### ISSUE THREAD

**Issue by Corben77** [greymass/eos-voter#186]
hello
whatever action I try with the wallet I get this error:

"XXXXXXXX","permission"."active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"]

now my funds are locked in GREYMASS and I cannot access them anymore

**Comment by ScottSallinen** [comment]
Did you import your owner key into the wallet? 
Unfortunately at the moment there is a bug with eosjs (Block One's JS signer) that doesn't allow us to sign with the owner key.

Can you try recreating your wallet with your active key instead?

**Comment by Corben77** [comment]
no idea - I used two different keys which I created with GREYMASS before. Unfortunately I transfered already a substantial amount of EOS to the wallet.

**Comment by ScottSallinen** [comment]
I hope you saved your keys somewhere..?
Try again with each key, only one is the active key.

**Comment by Corben77** [comment]
so how can I reimport the keys into the wallet? If I uninstall it and try a reinstall then I get the old setup.

**Comment by aaroncox** [comment]
Click the Greymass logo in the upper right corner, scroll to the bottom, and there's a "Delete Local Wallet" button. Hit that to reset the wallet to it's original installation state.
