### ISSUE TITLE
Cannot Vote

### ISSUE THREAD

**Issue by ojerscg** [greymass/eos-voter#187]
I keep getting a error when trying to submit my votes.  I keep getting this error with my account name and key in it.

"************","permission"."active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["**********************************************"]

Please help so I can please start voting.

**Comment by ScottSallinen** [comment]
See #186

**Comment by ojerscg** [comment]
By destroying it do I lose what I have moved to this wallet, like do I need to move my EOS back to an exchange to destroy this wallet?  Still new to this whole thing.

**Comment by aaroncox** [comment]
EOS isn't a typical key based blockchain where the keys hold the funds - your account holds those funds. 

As long as you have your private key, you can reimport it and your wallet will be exactly as it was.

**Comment by aaroncox** [comment]
Closing - can discuss further while closed if needed.
