### ISSUE TITLE
looking up account name

### ISSUE THREAD

**Issue by btsfav** [greymass/eos-voter#20]
entered my pubkey on testnet, but all I get is a:

![image](https://user-images.githubusercontent.com/15261692/40883914-6efe3572-6708-11e8-85d5-8235c0f571e9.png)

**Comment by aaroncox** [comment]
Yup, I think we see the issue. We will get it fixed in one of the next builds. 

By chance did you reset your wallet at any point?

**Comment by btsfav** [comment]
@aaroncox nope first time using it. no credentials added

**Comment by aaroncox** [comment]
Good to know - thanks. Well give it a shot from a fresh install to see if we can reproduce.

**Comment by aaroncox** [comment]
We have this fixed in 0.1.1 - which should be released here soon.
