### ISSUE TITLE
Odd wallet label for older wallets: global_modal_account_import_undefined_wallet

### ISSUE THREAD

**Issue by lukestokes** [greymass/eos-voter#204]
![image](https://user-images.githubusercontent.com/344748/42476301-20a7661c-8393-11e8-9d37-5913af98f170.png)

**Comment by aaroncox** [comment]
Hah - it seems we didn't catch all the edge cases in our schema upgrade. I'm assuming as soon as you imported a second account, then swapped back and forth, it resolved itself?

I'll add the strings for those so it's at least less confusing.
