### ISSUE TITLE
Network Resource Usage shouldn't be able to exceed 100% 

### ISSUE THREAD

**Issue by aaroncox** [greymass/eos-voter#22]
![image](https://user-images.githubusercontent.com/677686/40891844-12291d6e-675b-11e8-81a8-35a34b716cf2.png)

These values can currently go well above 100%, indicating that the user has used more than 100% of their indicated bandwidth or CPU. 

These elements perhaps should be reversed - when a user has used 0/X (where X is available max), they should show 100% available, and then drain down to 0% as the user consumes the resource.

**Comment by masterkrang** [comment]
mining? 😛

**Comment by aaroncox** [comment]
This is resolved in 0.1.1/0.1.2.
