### ISSUE TITLE
Send Tokens: symbol precision mismatch

### ISSUE THREAD

**Issue by jemekite** [greymass/eos-voter#222]
I just tried to send some IQ token to bitfinex and got this error message:

![capture](https://user-images.githubusercontent.com/1957943/42720187-c8b9bf50-874c-11e8-9a6f-189cd1eb961e.PNG)

tried with and without 4 digit decimal (x.0000), both failed.

**Comment by rudijs** [comment]
@jemekite I'm also trying and my google search led me here.

I only see EOS in the token list dropdown - do you see more than just EOS?

![greymass](https://user-images.githubusercontent.com/1711940/42721132-849a009e-8767-11e8-87fc-981313346774.png)

**Comment by aaroncox** [comment]
Version 0.3.3 should resolve this issue. Let us know if it doesn't for you - but that was the bug we specifically tried to fix with that release.
