### ISSUE TITLE
Change Owner Public and Private Key Pair

### ISSUE THREAD

**Issue by controllinghand** [greymass/eos-voter#225]
One of the great features in EOS is the ability to set Active Key pairs and Owner Key pairs associated with an account name.

Can you provide the ability to change ones Owner Key Pairs so that we can have the extra security?

EOSToolkit has this ability with scatter. 
https://steemit.com/eos/@genereos/eos-how-to-quickly-and-safely-change-your-public-private-keys

But I'm not a big fan of scatter chrome plug ins.  So....

**Comment by aaroncox** [comment]
We're planning on diving into permissions right after account creation - likely an 0.5.x build. 

Sorry about the delay on this one, it's one of the things we want to make sure we're getting right.

**Comment by controllinghand** [comment]
No worries.  You guys are on fire with all of the additions so far.  I'm so impressed keep up the great work.  You all Rock!

**Comment by aaroncox** [comment]
Hah no worries at all, I've done the same thing too many times to count. Github doesn't do the best job at making sure things are brought to the surface in a way that makes sense!

**Comment by aaroncox** [comment]
Available in 0.5.0
