### ISSUE TITLE
Please add IRESPO token from irespotokens smart contract as default

### ISSUE THREAD

**Issue by filipniziol** [greymass/eos-voter#228]
Our project is making an ICO in 2 weeks. 
We will be grateful if IRESPO token from irespotokens smart contract is added to greymass wallet as default.

**Comment by ScottSallinen** [comment]
Once you have created your token, feel free to add it yourself! See the header `Add to the table` and replace with your information:
https://github.com/greymass/customtokens

**Comment by aaroncox** [comment]
I'm sure someone will get it added as it's released, and the torrent of "where airdrop?" starts flooding in 😁

**Comment by filipniziol** [comment]
Done! Thank you! Nicely done with storing the tokens in smart contract and an option to add on your own!
