### ISSUE TITLE
Ram in account view bug.

### ISSUE THREAD

**Issue by cloudzombie** [greymass/eos-voter#230]
There is a bug with the value displayed in regards to amount of RAM held in account. 

I am looking in my account on an explorer, scatter on a ram trading site fee.explorer as well as the Greymass voter wallet.

**Comment by dafuga** [comment]
Hey @cloudzombie ! What is the bug that you are experiencing? Is it just the wrong amount?

**Comment by cloudzombie** [comment]
Scatter and https://eospark.com/MainNet/account/giydkmqgenes here both display a different value than my account in greymass shows. It shows 986KB while the other two show 962KB.

**Comment by slipo** [comment]
This account bought more RAM but before it had 986060 bytes of RAM.

eos-voter uses pretty-bytes as its library to convert that to `kB`. You'll see other sites are using `KiB` or `KB`

The author of pretty-bytes has dealt with these types of questions. He writes here https://github.com/sindresorhus/pretty-bytes/pull/5#issuecomment-61850376: 
> 'kB' is correct in this case, as this module uses base-10 (metric) units, so it represents 1000 bytes. 'KB' would only be correct in the case of it representing 1024 bytes.

He references the table on the right here: https://en.wikipedia.org/wiki/Kilobyte

986060/1024= 962.9

This is a classic point of confusion but technically I would say this isn't a bug. It does seem that most EOS apps are choosing to divide by 1024 so it may make sense to switch methods to avoid confusion.
