### ISSUE TITLE
I would like to install greymass wallet in my ubuntu and please tell me which one do I have to download.  

### ISSUE THREAD

**Issue by doubleconnect1** [greymass/eos-voter#232]
Which one is for Ubuntu?

36.5 MB linux-eos-voter-0.3.3-amd64.deb
104 MB linux-eos-voter-0.3.3-amd64.snap
33.8 MB linux-eos-voter-0.3.3-arm64.deb
34.9 MB linux-eos-voter-0.3.3-armv7l.deb
38.7 MB linux-eos-voter-0.3.3-i386.deb
52.1 MB linux-eos-voter-0.3.3-x86_64.AppImage

**Comment by aaroncox** [comment]
Any of them should work under ubuntu (I believe?), it's just a matter of installing based on which package management software you're most familiar with.

It's also available in the snapcraft store now - which you can browse and find, or install with `sudo snap install eos-voter`.
