### ISSUE TITLE
Ability to participate in AirGrabs

### ISSUE THREAD

**Issue by plouto5** [greymass/eos-voter#233]
Would love the option to be able to participate in the AirGrabs with the **Cold Wallet**. Maybe create a page where you can call wallet functions with a drop down or manually for a transaction output. 

cleos push action ridlridlcoin claim '["accountname"]' -p accountname

Your wallet is amazing and I appreciate all you guys have been doing!

**Comment by aaroncox** [comment]
This is now possible in v0.4.0+

![image](https://user-images.githubusercontent.com/677686/43350795-6fd27670-91d8-11e8-9d4b-7999a6a0b4a6.png)
