### ISSUE TITLE
"Private key does not match" It worked before (v0.1.5?), Now it does not (v0.3.3).

### ISSUE THREAD

**Issue by alexdimella** [greymass/eos-voter#234]
My private key WAS working with an early version of eos-voter app, now it is not working with the new version of eos-voter. It is the EXACT SAME and CORRECT Private Key (worked with the 1st install of eos-voter). I am not hacked. My funds are safe in the mainnet... for now. As viewed on eosflare.io (detailed below). 

Here are the details that got me here...

Mainnet launches
I downloaded greymass eos-voter app a few days later to vote.
Created an account and got an account name, used my one and only private key.
Private key worked- All of my EOS was there and staked in wallet.
When the vote was over, I then unstaked, waited over 3 days.
Logged back into eos-voter app to check and everything was where it should be.
Also checked eosflare.io for my funds and that was looking correct as well, along with some airdrops.
Since I noticed the airdrops, I went to the wallet to add tokens BUT the version I had did not have that feature (to add a Token) so I had to download the latest version...

AND HERE IS WHERE THE PROBLEM STARTS...

![privatekeydoesnotmatch](https://user-images.githubusercontent.com/36021306/42977214-e799a7c8-8b93-11e8-95b3-9b91b68692b9.jpg)

After installing the new version of eos-voter, it refuses to take my EXACT SAME private key that was used before. I never changed it. I tried connected and disconnected. This has to be a bug or something!?

Here is my public key where you can see my funds. It's all there, all transactions reported perfectly...

https://eosflare.io/account/gu3tcnrxhege
EOS5e7o9VCJYo4hch5KxDA69Mh48J1KZFNUuDfSQ4f5n6DuHc8krh

I still have my ERC20 keys that I used to register my EOS pre-mainnet.

What should I do next? Thank you so much for your time to read this.
-Alex

**Comment by aaroncox** [comment]
From the screenshot above - it doesn't look like the private key you are entering matches the private key on record. 

I'd recommend trying a secondary tool, like:

https://github.com/eoscafe/eos-key

To validate that your keys actually resolve to: 

`EOS5e7o9VCJYo4hch5KxDA69Mh48J1KZFNUuDfSQ4f5n6DuHc8krh `

**Comment by alexdimella** [comment]
@aaroncox Thanks Arron! I'll check it out.

**Comment by aaroncox** [comment]
Closing issue, can reopen if the problem surfaces again.
