### ISSUE TITLE
APPCRASH win-eos-voter-0.3.3.exe

### ISSUE THREAD

**Issue by Auggie1** [greymass/eos-voter#247]
Well, after the avast reporting a problem and setting .3.3 as an exception I'm still having a problem installing it. This is the error report that Win 7 is giving me. Any suggestions?
Thank you, Auggie

Problem signature:
  Problem Event Name:                        APPCRASH
  Application Name:                             win-eos-voter-0.3.3.exe
  Application Version:                           0.3.3.0
  Application Timestamp:                    5a6fed7c
  Fault Module Name:                          System.dll
  Fault Module Version:                        0.0.0.0
  Fault Module Timestamp:                 5a6fed15
  Exception Code:                                  c0000005
  Exception Offset:                                00001581
  OS Version:                                          6.1.7601.2.1.0.256.48
  Locale ID:                                             1033
  Additional Information 1:                  0a9e
  Additional Information 2:                  0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:                  0a9e
  Additional Information 4:                  0a9e372d3b4ad19135b953a78882e789

**Comment by aaroncox** [comment]
Avast seems to have a lot of problems with our app lately - and we're looking into why but don't have a lot of answers yet. We have a few things we plan on trying in 0.4.2+, but in the mean time I'd just recommend disabling avast temporarily while you install. Hopefully it won't sandbox it and break it after it reenables itself.
