### ISSUE TITLE
Seeing net::ERR_SPDY_PROTOCOL_ERROR connecting to a valid API endpoint

### ISSUE THREAD

**Issue by robrigo** [greymass/eos-voter#269]
Hello Team Greymass!

I wanted to raise an issue that I'm seeing on version 0.4.1 of eos-voter. Perhaps you can help me resolve it. Recently, I configured the haproxy LB that https://api.eosdetroit.io uses to enable HTTP/2. I am not 100% if this is configured correctly, however I am able to use our API endpoint to interact with the EOS mainnet using cleos without an issue. However, when I try to configure that endpoint for eos-voter, `net::ERR_SPDY_PROTOCOL_ERROR` is thrown in the console. See below for a demo.

![eos-voter-spdy-bug](https://user-images.githubusercontent.com/590263/43357711-d546a122-9253-11e8-823e-8659f6e74afa.gif)

**Comment by aaroncox** [comment]
Thanks @robrigo. I'm seeing the same errors, and I'm not entirely sure where the source of the problem exists. I'm starting to look into it and can report if I end up finding a solution. 

One thing that might be worth considering is that SPDY I believe is deprecated in favor of HTTP/2. We're using an nginx proxy in front of our API nodes and using HTTP/2 - if you're interested in how we're setup, we're happy to share!

**Comment by robrigo** [comment]
Thanks for the response @aaroncox! All I've done at this point is enable HTTP/2 at the haproxy layer on our proxy node, that is sent through patroneos and then passed along to our nodeos configured for a full node.

My hunch is that my current configuration is broken somewhere in that lifecycle, and the error would likely be obscured if I had fallback to HTTP 1.1 configured. I do appreciate any insights you have into your setup though. :)

**Comment by robrigo** [comment]
Thanks for sharing that debugging tool and config @aaroncox. I'll let you know what I find when I get back to looking at this.

**Comment by aaroncox** [comment]
Closing this out, but feel free to ping me with any issues 👍
