### ISSUE TITLE
Incorrect peer dependencies

### ISSUE THREAD

**Issue by kargakis** [greymass/eos-voter#271]
```
[3/4] Linking dependencies...
warning "stylelint > postcss-html@0.23.7" has incorrect peer dependency "postcss-syntax@^0.10.0".
warning "stylelint > postcss-markdown@0.23.7" has incorrect peer dependency "postcss-syntax@^0.10.0".
```

**Comment by aaroncox** [comment]
These are pretty deep dependencies that I don't think we have control over specifically. 

I'll see if upgrading the version of `stylelint` we're using ends up resolving it though.

**Comment by aaroncox** [comment]
I haven't seen this error in recent builds either, I believe this one is resolved with the update. Reopen if the problem persists.
