### ISSUE TITLE
Create new global memo field component

### ISSUE THREAD

**Issue by aaroncox** [greymass/eos-voter#275]
The new memo field component should have validation that includes:

- [x] maximum length validation
- [x] rejects any memo that contains anything that resembles a private key (starts with `5` and 51 characters). 
- [x] can be empty - except when an exchange is specified as the `to` field

**Comment by aaroncox** [comment]
@dafuga can you confirm these 3 are done and close?

**Comment by dafuga** [comment]
Yep! That's all done @aaroncox !

**Comment by dafuga** [comment]
I'm going to go ahead and close it!
