### ISSUE TITLE
Tools: Delegation Management

### ISSUE THREAD

**Issue by aaroncox** [greymass/eos-voter#278]
Create a new tool for Delegation Management. 

Should be:

- [x] a table of all outstanding delegations (including to self)
- [x] details on each delegation in terms of amount (and whatever other values are available)
- [x] display showing returning delegations
- [x] button to revoke delegation on each table row
- [x] button to alter delegation on each table row
- [x] button on the top of the UI to create a new delegation (from, to, cpu, net, transfer (bool) as fields)

**Comment by dafuga** [comment]
@aaroncox since the returning delegations are already displayed on the stats section of the wallet as well as on the of the stake form, can we consider this issue done?

**Comment by aaroncox** [comment]
I think so! I'll mark it as such..
