### ISSUE TITLE
APPCRASH on Windows 7

### ISSUE THREAD

**Issue by KrNel** [greymass/eos-voter#290]
Version: win-eos-voter-0.4.1.exe

Behavior: Double-click, click Run, and it crashes immediately with the following information displayed:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	win-eos-voter-0.4.1.exe
  Application Version:	0.4.1.0
  Application Timestamp:	5a6fed7c
  Fault Module Name:	System.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5a6fed15
  Exception Code:	c0000005
  Exception Offset:	00001581
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

If you need additional information, please let me know. Thank you.

**Comment by KrNel** [comment]
I installed an older version I had downloaded but never installed, 0.1.7, then the new installer worked. Must have been a fluke. Please disregard. Thanks.

**Comment by aaroncox** [comment]
Could a virus scanner be quarantining the executable?

We added win-32 support bundled in the EXE in one of the 0.3.x releases and it seems to be triggering all sorts of alerts from things like avast.

**Comment by KrNel** [comment]
I don't have an anti-virus installed, so it's not that. I just use the 0.4 version since it works.

**Comment by aaroncox** [comment]
Closing this out as it seems resolved. Feel free to open a new issue if one of the newer versions does something similar.
