### ISSUE TITLE
Can't run AppImage. Segmentation Fault.

### ISSUE THREAD

**Issue by treepi3** [greymass/eos-voter#296]
When trying to run the latest eos-voter appimage on Manjaro, I get a Segmentation Fault (core dumped) error in the terminal.

That is all it says. Can't find any reports of this anywhere else. Ideas?

**Comment by treepi3** [comment]
@aaroncox oddly, just updated Manjaro again this morning and the appimages started working again. Pretty odd lol.

**Comment by aaroncox** [comment]
Yeah - it really is. There's so many variations of linux it's hard to keep track of why one version does something weird over another. 

Closing this out.
