### ISSUE TITLE
does not have signatures for it under a provided delay of 0 ms

### ISSUE THREAD

**Issue by tristanbuist** [greymass/eos-voter#305]
Hello,

When using your 'EOS Voter - 0.4.1' software on windows - when I go to either; 'update staked EOS' or vote for block producers, after hitting 'confirm' I get the following error message:

"tristanbuist","permission"."active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["EOS8Ac9LqYC7oR2qjfTBZT3kVbpNcGSJiSW53Z6JmJJ22uTtPRxyp"]

This is a new account. I have another account which I can log into where I do not get these errors.

Can you help? I am not an IT person, just a user so please try to answer accordingly

Thanks very much.
Tristan

**Comment by aaroncox** [comment]
This typically happens if you have the private owner key imported into the wallet, when it's expecting the private active key. 

Assuming you have 2 different private keys (starts with a `5`), try removing/resetting your wallet (Click the Greymass logo in the upper right, scroll to the bottom, click the "delete credentials" button) and then restart the import process using the private active key.

**Comment by tristanbuist** [comment]
Thanks very much for your quick and helpful response.

I bought this account from 'namevault' where I believe I was only given the one 'private key'. ( had a mini heart attack when I couldn't login to EOS voter after deleting me credentials!)

I can still get into my account because I have the private key, just not the two different keys? I have messages 'namevault' for their assistance.

Thanks again
Tristan

**Comment by aaroncox** [comment]
It sounds like they gave you the owner key, and just not the active key. We've seen a few sites that seem to do this for some reason. 

If you download our 0.5.0RC2 release from github and install that, you can update the active key to a new key you control. 

1. Install newest version: https://github.com/greymass/eos-voter/releases/tag/v0.5.0RC2
2. Import your owner key as you have been. 
3. Click Tools, then Key Generator. 
4. Click the Generate Key button to create a new key pair. This will be what we set your new active keypair to in the next step. Back this up someplace safe along with your owner key (that you have).
5. Now on the Permissions menu item on the left.
6. The 2nd box shows which key you're currently using, which should match what's in the `owner` box.
7. You'll see your two permissions, find the `active` one and click the Modify button.
8. Paste the PUBLIC key you generated in Step 4 and click "Update Permission".
9. A success message should appear with a transaction ID, if it does not, let me know and do not proceed to the next steps.
10. Reset the wallet again using the Delete Credentials button (which is now also on the tools page, under the "Reset Application" menu item on the left).
11. Import your account, except this time, use the PRIVATE key you generated in Step 4.
12. You should now have a wallet with the active key loaded, and be able to perform any actions you'd like!

Hope that works, and if not, let me know where you get stuck.

**Comment by tristanbuist** [comment]
Thank you aaroncox

A very helpful and easy to follow guide. I very much appreciate your help!

greymass for top 21!!!!!!!^^
