### ISSUE TITLE
Support for custom EOSIO-based prefixes (EOS, TLOS, etc)

### ISSUE THREAD

**Issue by marlonwilliams** [greymass/eos-voter#314]
Hi Team,

Great work on this fantastic wallet.

I'm submitting this issue to request support for EOSIO-based prefixes (specifically in support of Telos). We've submitted a pull request to the eosjs-ecc repo, which was merged and pushed to npm, that supports custom prefixes for EOSIO public keys. Details can be found here: https://github.com/EOSIO/eosjs-ecc/pull/30

Can this be scheduled in with your next release?

**Comment by aaroncox** [comment]
Available in 0.6.0 - release soon.
