### ISSUE TITLE
Error trying to Stake EOS

### ISSUE THREAD

**Issue by controllinghand** [greymass/eos-voter#331]
![image](https://user-images.githubusercontent.com/31561227/44565982-d68a1b00-a71f-11e8-8441-303ccc054c8c.png)

I'm getting this error when I try to stake EOS

Can you help?

Thanks
~S

**Comment by aaroncox** [comment]
Which version are you running? I believe 0.5.1 has a better error log output screen - if you're not running that version, upgrade and it might show a bit more detail about what error is actually occurring.

**Comment by controllinghand** [comment]
Ok.  I think it has something to do with the amount I'm staking.  When i just did a few eos it took.  But when I tried to do 1000 it failed.  I think it's a resource issue.

**Comment by controllinghand** [comment]
I'll update the version.  I'm on 0.5.0

**Comment by controllinghand** [comment]
Hmm.  I just update to 0.5.1 and now I'm able to stake 1000.  I'm not sure if it was the upgrade or the internal error just resolved.  Sorry i can't help more.  If it pops up again on this version I'll let you know.

Keep rocking!

~S

**Comment by controllinghand** [comment]
Closing issue as I know you have a lot on your plate.

**Comment by aaroncox** [comment]
Might have been a bug fix we deployed, who knows but glad it's resolved!
