### ISSUE TITLE
 Integrating the new `codeaccounts` contract with transfers.

### ISSUE THREAD

**Issue by dafuga** [greymass/eos-voter#336]
We are going to need to display a warning on transfers if the recipient account has a smart contract enabled, and warn them that “The destination account has a smart contract enabled, and by sending to this account, your transfer may trigger additional actions which could consume RAM”.

**Comment by ScottSallinen** [comment]
Consider using new feature, `get_code_hash`:
https://github.com/EOSIO/eos/pull/5434

e.g. 
```curl https://eos.greymass.com/v1/chain/get_code_hash -d '{"account_name" : "producerjson"}'```

Works to figure out the account status -- if there's a hash, there's a contract!

**Comment by aaroncox** [comment]
Available in 0.6.0 - release soon.
