### ISSUE TITLE
Is the number/percentage of EOS Staked Globally accurate?

### ISSUE THREAD

**Issue by comfyowl** [greymass/eos-voter#342]
These following sites offer different statistics.
The value from eos-voter seems 'stuck'
https://eosauthority.com/voting
http://eosnetworkmonitor.io/

**Comment by aaroncox** [comment]
I don't believe so - but it's what's being returned by the API from the globals table. 

We're planning on reworking that header element with more relevant information. We build that UI while we were waiting for the 15% staked to initialize the chain :)

**Comment by aaroncox** [comment]
The header has at least been removed, the UI rework is coming soon.
