### ISSUE TITLE
cannot find other tokens from pull down menu 

### ISSUE THREAD

**Issue by s002858** [greymass/eos-voter#344]
Only Eos can be found. Other tokens cannot be found during "transfer token" menu

**Comment by aaroncox** [comment]
You'll need to track them first, by visiting "Tools" and then "Airdrops / Custom Tokens". After you select which to track, they'll appear in the dropdown if you have a balance.

**Comment by s002858** [comment]
Hi, Aaron,

 

I have made it. 

 

Thanks you. 

 

Jimmy 

  _____
