### ISSUE TITLE
Ledger Nano S integration

### ISSUE THREAD

**Issue by volschin** [greymass/eos-voter#346]
Do you see an option also to integrate Ledger Nano S as done by https://github.com/tarassh/fairy-wallet ?

**Comment by wallet-sdk** [comment]
Can you consider having some kind of a cold wallet plugin api? To allow simply integrating of other cold wallets?

**Comment by aaroncox** [comment]
Yeah I think we can probably make it work with other cold wallets, provided they use the same unsigned transaction format. It sounds like we (the developer community) need to come up with a standard file format for all wallets to interpret. It's a bit outside of the scope of this issue, but something we've been thinking on.

**Comment by aaroncox** [comment]
Available in 0.6.0 - release soon.
