### ISSUE TITLE
Error Sending EDNA Tokens to Another EOS Account

### ISSUE THREAD

**Issue by insalaco** [greymass/eos-voter#353]
Sending EDNA tokens to another EOS wallet causes an error.

eos-voter version 0.5.1 MacOS

"ERROR: transaction must have at least one authorization". 

![screen shot 2018-09-16 at 6 22 35 pm](https://user-images.githubusercontent.com/934208/45702784-ae37e580-bb40-11e8-95d5-8eccc5b009c7.png)

**Comment by aaroncox** [comment]
This should now be resolved in the newly released 0.5.2 - please reopen if the problem persists.
