### ISSUE TITLE
option to paste a signed transaction for transmitting

### ISSUE THREAD

**Issue by jeee** [greymass/eos-voter#367]
Instead of opening a file be able to paste clipboard contents directly.

**Comment by aaroncox** [comment]
Sorry for the delayed response, but this is a great idea. We'll try to get it implemented in one of the next release or two. 

You have any specific use cases in mind with other apps?

**Comment by jeee** [comment]
You can use it to transmit signed transmissions from cold storage. Would even be better if that was also included in your website like https://etherscan.io/pushTx

**Comment by aaroncox** [comment]
Available in 0.6.0 - release soon.
