### ISSUE TITLE
Token transfer error

### ISSUE THREAD

**Issue by jbl777** [greymass/eos-voter#370]
Hello,
I've tried to transfer IQ token to outside wallet from EOS voter wallet(GREY MASS) and encountered an error as follows:

{"code".500,"message"."Internal Service Error","error".{"code".3100008,"name"."unsupported_feature","what"."Feature is currently unsupported","details".[{"message"."Returning WAST from get_code is no longer supported","file"."chain_plugin.cpp","line_number".1538,"method"."get_code"}]}}png)

Please let me get how to resolve this error. 

Thanks in advance.

**Comment by ScottSallinen** [comment]
Are you on Version 0.5.3? Please check if upgrading solves this problem!

**Comment by jbl777** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thanks for your reply. 
Per your advice I upgraded the version to 0.5.3 and resolved the error.

However I have another issue as follows:

1) I tried IQ token transfer and got a txid with the message as below.﻿


2) then I explored the txid and I got a message "Transaction not Found". My transfer had not been succeeded. 

TXID: 383265c040b8f19a13bef08042ec1b9f969736572aa20472d60f3af102c7ee7d
﻿
Do you have any ohter advice fo rme? 

Thanks a lot.﻿


--------- 원본 메일 ---------

    
        보낸사람: Scott Sallinen <notifications@github.com>
        받는사람: greymass/eos-voter <eos-voter@noreply.github.com>
        
            참조: jbl777 <jbl777200@hanmail.net>, Author <author@noreply.github.com>
        
        날짜: 18.09.27 06:31 GMT +0900
        제목: Re: [greymass/eos-voter] Token transfer error (#370)
        
        
    
    
        Are you on Version 0.5.3? Please check if upgrading solves this problem!

**Comment by ScottSallinen** [comment]
It's possible it was sent during a hiccup in the network. Try sending it again and see if it disappears again.

**Comment by aaroncox** [comment]
Closing, but reopen if the issue persists.
