### ISSUE TITLE
Desktop Launcher bug

### ISSUE THREAD

**Issue by StevenAbaby** [greymass/eos-voter#375]
see results below:
steve@steve-Inspiron-5721 ~/Downloads/greymass $ cat /etc/os-release
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial
steve@steve-Inspiron-5721 ~/Downloads/greymass $ ls -l
total 107312
-rw-r--r-- 1 root  root          0 Oct  3 13:59 }??
-rwxrwxr-x 1 steve steve 109862912 Oct  3 13:56 linux-eos-voter-0.5.3-amd64.snap
steve@steve-Inspiron-5721 ~/Downloads/greymass $ sudo ./linux-eos-voter-0.5.3-amd64.snap 
./linux-eos-voter-0.5.3-amd64.snap: 2: ./linux-eos-voter-0.5.3-amd64.snap: hsqs�N��[�-u�[��[����������ˉB�
                                                                                                                       !�O[��7zXZi"�6��!
�*"�#�]!���w�f��}�%�sD�)�^Y��يE��ҋU��� �s;�U-�)��#��霐_y��: not found
./linux-eos-voter-0.5.3-amd64.snap: 3: ./linux-eos-voter-0.5.3-amd64.snap: Syntax error: "(" unexpected (expecting ")")
steve@steve-Inspiron-5721 ~/Downloads/greymass $

**Comment by aaroncox** [comment]
We have stopped distributing snaps until a few bugs like this get resolved. Apologies for the delayed response, but I'd recommend using the AppImage for the time being.
