### ISSUE TITLE
Automatically unselect BPs that are no longer registered during voting

### ISSUE THREAD

**Issue by aaroncox** [greymass/eos-voter#380]
> https://twitter.com/Devo144/status/1049464067461664768
> When I vote and get the error that one of the bp's isn't registered, it would be awesome if you could show me which one it could be. Could that be possible?

We should probably:

- notify the user somehow if one of the BPs they vote for is no longer registered
- if the user attempts to cast a vote with a BP that's unregistered, automatically remove it from the votes about to be cast and display it's removal in the confirmation

**Comment by aaroncox** [comment]
Automatic removal of invalid votes is coming in 0.6.6 - though the UI still needs to inform the user of it.

**Comment by aaroncox** [comment]
Additional UI thoughts:

My thoughts are:

- Everytime the user’s current votes is processed, we compare that against the list of all producers loaded (if producers are done loading).
- If it finds a producer voted for that’s missing in the list, it appends it to a new array in the producers reducer, maybe called `unregisteredProducers`.
- We add a new conditional sidebar element above the “who I vote for list”, that has the producers inside the `unregisteredProducers` array.
- The same element is used to render this new list, which has a button to unvote them.
- We probably also need a check on vote casting, that prevents them from confirming if one of the producers in that list is also in the new array.

**Comment by dafuga** [comment]
Addressed in PR #495
