### ISSUE TITLE
EOS transfer

### ISSUE THREAD

**Issue by rami4winds** [greymass/eos-voter#381]
Hi there, new on here so just trying to figure it out. I'd like to transfer my EOS from MEW to here so I can cash my tokens in. Is this doable in Github? Please help.

**Comment by rami4winds** [comment]
Hey Arron,

Ok so I see what you're saying and understand. I also see I have on the EOS
Authority site my account with the EOS tokens and whole bunch of airdrop
tokens too. So I can send those  EOS tokens to my Kraken account from there?

Rami

**Comment by aaroncox** [comment]
Yes, you'd just need to use a wallet with the EOS private key (starts with the number 5), and you'd be able to transfer those tokens.

**Comment by JB2426** [comment]
How does one locate the new keypair you referred to Aaron please? I'm in the same situation having bought a batch of Cryptos and tokens in April 2018 and didn't get any notification about the changeover. 
THANKS

**Comment by aaroncox** [comment]
If you didn’t register for the ERC20 to mainnet transition, this is a good starting position:

https://medium.com/eos-new-york/unregistered-eos-tokens-recovery-method-80580e1b219b

There are a number of guides out there on how to claim unregistered tokens, you can google for “EOS fallback method” to see a lot more on the topic.

**Comment by JB2426** [comment]
Many thanks!
________________________________
