### ISSUE TITLE
Referendum Improvements

### ISSUE THREAD

**Issue by aaroncox** [greymass/eos-voter#403]
- [x] Allow filtering of proposals by current account votes: All (default), Supported, Rejected, Unvoted
- [x] Allow filtering of proposals by status: Active (default), Expired
- [x] Search by: Proposer, Proposal ID
- [x] Show ricardian contracts
- [x] Add links to external sources to read the details of the proposal.
- [x] Help section with full writeup and more information about how the system works.

**Comment by dafuga** [comment]
These changes will all be deployed in the next release (0.7.5).
