### ISSUE TITLE
Update permission - "internal service error" - code 500

### ISSUE THREAD

**Issue by NGPF** [greymass/eos-voter#415]
Hello,
While updating active permission (account permissions on eos-voter 0.6.0 for OSX connected to https://eos.greymass.com node) I continuously get the following error:
```
Error
{permission}

{
"code":500
"message":"Internal Service Error"
"error":{
"code":3040000
"name":"transaction_exception"
"what":"Transaction exception"
"details":[
0:{
"message":"action's authorizations include a non-existent permission: {permission}"
"file":"controller.cpp"
"line_number":1833
"method":"validate_referenced_accounts"
}
]
}
} 
```
Any ideia on how to fix this issue would be great!

Thanks

**Comment by aaroncox** [comment]
Hrm, which permission (owner/active) are you trying to update, and which permission (owner/active) do you have loaded?

**Comment by NGPF** [comment]
Trying to update active with owner loaded.

**Comment by aaroncox** [comment]
Sorry I dropped off on this - is this using temporary mode or is the key encrypted into the wallet with a password?

I'll try to reproduce the issue locally. 

One thing to try that might fix it is resetting the wallet (Tools -> Reset App at the bottom) and reimporting everything. Sometimes during the upgrades things get upgraded funny.

**Comment by NGPF** [comment]
Hello Aaron, thanks for your help.

> Sorry I dropped off on this - is this using temporary mode or is the key encrypted into the wallet with a password?

It is while using the key encrypted into the wallet with a password.

> One thing to try that might fix it is resetting the wallet (Tools -> Reset App at the bottom) and reimporting everything. Sometimes during the upgrades things get upgraded funny.

Did the application reset, but problem persists.

**Comment by aaroncox** [comment]
I'll do some testing today to see if I can reproduce! We're planning a 0.6.2 release, and if I can get it fixed quickly, it'll be in todays release.

**Comment by NGPF** [comment]
Thanks Aaron, looking forward to get the release.

**Comment by JeanOffman** [comment]
Hello, I have the exact same issue. I'm using temporary mode though. The error log is exactly the same pasted by NGPF

**Comment by aaroncox** [comment]
I have a fix for this and it will be bundled in the release happening today (0.6.2). 

The fix will likely require removing the local wallet and reimporting the key, to allow the proper settings to be set and resolve the issue. 

If after 0.6.2 and reimporting your account it still does not work - please let us know!

**Comment by NGPF** [comment]
Thanks Aaron! Working perfectly
