### ISSUE TITLE
Ledger Claim Unstaked Balance Error 

### ISSUE THREAD

**Issue by eosz** [greymass/eos-voter#425]
I'm getting this error and am unable to claim refund, any idea why, thanks?  Invalid data received (0x6a80)

Update: got it to work, make sure you have Greymass 0.6.1 and eos ledger app version 1.1.0 installed on device and enable arbitrary data in menu, thanks greymass for solving this 👍

**Comment by aaroncox** [comment]
I should probably have added that to the release notes :)
