### ISSUE TITLE
search doesn't match producer names

### ISSUE THREAD

**Issue by aaroncox** [greymass/eos-voter#43]
The search is only matching the beginning of strings right now. If you search for `greymass`, `teamgreymass` doesn't appear since it starts with `team`. 

Searching should allow for more fuzzy matches to help find what voters are looking for.

**Comment by ScottSallinen** [comment]
I was unable to reproduce this in Windows. `team` returned `teamgreymass` as an option, as expected.

**Comment by aaroncox** [comment]
Yeah after further testing, this appears to be a false alarm. Not sure exactly what was happening when the user reported it was searching. There may be some sort of bug here, but not enough information to proceed.
