### ISSUE TITLE
Error Transferring EOS assets

### ISSUE THREAD

**Issue by bigone11** [greymass/eos-voter#434]
While attempting to transfer a custom token I added (which was verified and shows it being in my wallet) from an airdrop I received this error message:

{"code".500,"message"."Internal Service Error","error".{"code".3100008,"name"."unsupported_feature","what"."Feature is currently unsupported","details".[{"message"."Returning WAST from get_code is no longer supported","file"."chain_plugin.cpp","line_number".1538,"method"."get_code"}]}}

Does EOS voter 2 not allow for transfer of EOS-asset tokens that aren't EOS itself?

**Comment by aaroncox** [comment]
That error gets returned if you're using an old version of the wallet. A couple months ago there was a change to the way contracts are processed (like custom token contracts) which requires an upgrade to correct.

Updating the app should resolve this issue.

**Comment by bigone11** [comment]
That fixed it, i thought i was on the latest version but i wasnt. Thank you!
