### ISSUE TITLE
History Fails to load

### ISSUE THREAD

**Issue by AALS007** [greymass/eos-voter#436]
History broadcast is failing to load properly , loads in and out.

**Comment by aaroncox** [comment]
We had a failure in our history API node, and the entire network is feeling the effects of it right now since it's consolidated down to just a few other history nodes. Requests should occasionally work still, but response times are going to be slow. 

We're working on it though.

**Comment by AALS007** [comment]
thank you Aaron,

**Comment by aaroncox** [comment]
Closing this out, our history node has been back online since last week and issues should have been resolved with that event.
