### ISSUE TITLE
Backup or Copy or Export Private Key

### ISSUE THREAD

**Issue by meshfields** [greymass/eos-voter#438]
I need to sell my PC. I need my Wallet. How can I convince Greymass to give it to me? I need my Privat Key. There is no Priv Key Backup since I created it within Greymass. Please help this is serious! I also would accept the encoded wallet file, since I have my password. I remember with BTC things very easy. Take that wallet.dat and you are done.

How can I save my EOS from getting lost? Need to ship my Win-based PC out tonight. My EOS are staked, I unstaked them now, but this takes 3 days.

**Comment by aaroncox** [comment]
You don't have your private keys saved externally? This app generally just imports the keys you specify, it doesn't actually create it's own set of keys. So whatever keys you imported are still the same keys your account uses. 

We do plan on adding export functionality at some point, but it's not ready yet. 

I'm not entirely sure if this works or not, but you can copy the entire `eos-voter` folder out of your local computer, and it may be possible to drop that folder on a new machine to restore your wallet. Again - this is untested, but you're asking for solutions in a very small windows of time.

- Click Start -> Run (or Windows + R hotkey)
- Enter `%APPDATA%` in the run prompt
- A folder will open that contains application data for a number of your applications.
- Copy the `eos-voter` folder, the `config.json` file within that folder has your encrypted wallets.

**Comment by meshfields** [comment]
Thanks a lot for this, I am trying this out as we speak and will report back, so that others can benefit from this unsupported workaround. I wonder why my stored Pub Key does not match the Pub Key in EOS Voter though. Kinda Scary.

**Comment by aaroncox** [comment]
You may want to make sure you have the latest version before doing this as well, or at the very least install the same version on the new machine as exists on the old.

**Comment by aaroncox** [comment]
Fantastic 🎉 

TIL - and so happy it works.
