### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by nanonano7** [greymass/eos-voter#44]
I think adding the option to have multiple accounts would be quite useful to some.

**Comment by aaroncox** [comment]
While I don't have a timeframe for it's release, it's near the top of our list of priorities to get added. We will update/close this issue as it's released!

**Comment by controllinghand** [comment]
You did it!  WOOT!  Love the update

**Comment by aaroncox** [comment]
Took a bit longer than we hoped, but completed in 0.3.0.
