### ISSUE TITLE
Chinese writing

### ISSUE THREAD

**Issue by SeanBur90** [greymass/eos-voter#440]
My wallet just changed some text to chinese. Is this intentional?

**Comment by aaroncox** [comment]
Nope, but you can change languages in the Settings. 

![image](https://user-images.githubusercontent.com/677686/48576947-e01cbc80-e8e3-11e8-83f3-845d0134f1c9.png)

**Comment by aaroncox** [comment]
Closing out, reopen if the problem persists.
