### ISSUE TITLE
Cannot vote - keep getting error message 3050003 producer_is_not_currently_registered

### ISSUE THREAD

**Issue by Stephen-LoT** [greymass/eos-voter#448]
Trying to vote and below error message keeps popping up and stopping the vote process. How do I resolve? Thanks S

Error
producer_is_not_currently_registered

{
"code":500
"message":"Internal Service Error"
"error":{
"code":3050003
"name":"eosio_assert_message_exception"
"what":"eosio_assert_message assertion failure"
"details":[...]
}
}

**Comment by Stephen-LoT** [comment]
I just tried it by eos toolkit and got this:

Failure
Transaction has failed

Details:
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3050003,
    "name": "eosio_assert_message_exception",
    "what": "eosio_assert_message assertion failure",
    "details": [
      {
        "message": "assertion failure with message: producer is not currently registered",
        "file": "wasm_interface.cpp",
        "line_number": 934,
        "method": "eosio_assert"
      },
      {
        "message": "pending console output: ",
        "file": "apply_context.cpp",
        "line_number": 72,
        "method": "exec_one"
      }
    ]
  }
}

**Comment by ScottSallinen** [comment]
Hey, it sounds like one of the producers you are trying to vote for has unregistered themselves as a producer. This means the TX will fail.
We're working on a better way to handle this error, but in the meantime you can simply identify which producer no longer exists (or just unselect everyone) and then re-select producers.
