### ISSUE TITLE
Documentation: OS X minimum version requirement?

### ISSUE THREAD

**Issue by bracklanna** [greymass/eos-voter#449]
Please add somewhere on the website, or on the github page, what the minimum OS version requirements are for the current release of Eos Voter.

I.e. does it work with OS X 10.9 and later? 10.10 and later? 10.12 and later? Requires Mavericks 10.13?

**Comment by aaroncox** [comment]
Do you have a version of OS X that it's not working on? As far as I'm aware, it should work on any modern version.

**Comment by dafuga** [comment]
Will close this since we are unaware of a OS X version on which the app doesn't run. If you think that's not the case, feel free to reopen another issue in the future.
