### ISSUE TITLE
eosio_assert_message_exception

### ISSUE THREAD

**Issue by sorinpohontu** [greymass/eos-voter#45]
Using latest version, on MacOS 10.13.4. 

Producer Voting -> Submit changes to blockchain -> Submit votes, I've got an error:

3050003: eosio_assert_message_exception
eosio_assert_message assertion failure

Wallet API Url: http://api.eosnewyork.io
My selection: 30/30 total votes cast

**Comment by Gutalean** [comment]
I have the same error in Linux. It happens when I vote for some specific BP(s). If I choose other BP the tool works fine.

**Comment by aaroncox** [comment]
Interesting, we're seeing multiple reports of this today. 

Any idea which specific votes were being cast that could be causing this? We'll be doing some testing to see if we can reproduce to find the exact error.

**Comment by capitalcrypto** [comment]
Unselect, then reselect the same bp. It worked for me the second time around. It took me a while to decide first time. Maybe theres a timeout?

**Comment by Gutalean** [comment]
I have error when voting for BP with 'None' vests and 0,00% in total votes.

**Comment by wurzelpanzer** [comment]
I just removed eosdublin (only voting for 29/30 BPs) which worked.
After adding eosdublin, which is the one with the least votes of my list of 30 atm, if fails with above error message. can supply my whole BP list if necessairy.
I dont think its a timeout.

**Comment by PaulRBerg** [comment]
I selected 20 BPs, switched to Wallet as I was getting the error, and when I returned I had zero selections. When I went through the process again, it worked.

I know as a fact I didn't have eosdublin in neither case from above.

**Comment by aaroncox** [comment]
It's a generic error message being reported by `nodeos`, which we've wrapped in an error handler to better address in 0.1.6. We won't be able to display exactly what that error is until it's reported accurately.
