### ISSUE TITLE
Error when changing non-standard active key

### ISSUE THREAD

**Issue by ColinTalksCrypto** [greymass/eos-voter#454]
I am trying to change my non-standard active key ("colintcrypto@active") to a normal key. But when I type a new active key, I get the error shown in the final image.

![greymass - image 1 - account permissions](https://user-images.githubusercontent.com/44652168/49742129-dded1a00-fc65-11e8-9b2a-adb32c8e20cd.PNG)
<img width="551" alt="greymass - image 2 - set new active permission" src="https://user-images.githubusercontent.com/44652168/49742130-dded1a00-fc65-11e8-86de-87e543c332f2.PNG">
<img width="532" alt="greymass - image 3 - error message" src="https://user-images.githubusercontent.com/44652168/49742131-dded1a00-fc65-11e8-8a47-8a002a499c8e.PNG">

**Comment by aaroncox** [comment]
Ahhh, good catch. I think it's mishandling the account based auths you've got set on the account. 

We'll get a fix out for this.

**Comment by ColinTalksCrypto** [comment]
Ok that would be awesome! It's definitely not a normal auth!

**Comment by ColinTalksCrypto** [comment]
Thank you. It worked and I was able to change my Active key with the latest
version of Greymass wallet.

Sincerely,
Colin

**Comment by woutercoding** [comment]
Hello, I have been experiencing the same error when trying to change the public key for owner permissions. But reading you thread I dont understand how to proceed... I'm an absolute beginner in coding etc. Could you please clarify once more? Kind regards, Wouter

![screen shot 2019-02-26 at 22 17 45](https://user-images.githubusercontent.com/47090604/53448142-ff64d300-3a16-11e9-9a59-0aeb6bddfce8.png)

**Comment by aaroncox** [comment]
@woutercoding - From the looks of it, you have the `active` key loaded up (or at least the wallet thinks so). Updating the `owner` key requires the `owner` key to be loaded.

Go into Tools -> Manage Wallets, and hit the button in the upper right to import a new account. Enter the private key for the `owner` permission and then check the checkmark for `accountname@owner` when it pops up. 

You can then use the dropdown in the top left to swap wallets to the `accountname@owner` permission and then you should be able to perform the action.

**Comment by woutercoding** [comment]
Thank you for your reply Aaron, and the effort spent. It tackled the problem!
Kind Regards, Wouter
