### ISSUE TITLE
after updating to 0.6.3 not able to vote, send or receive EOS, or update stakes

### ISSUE THREAD

**Issue by twomoretoo11** [greymass/eos-voter#455]

**Comment by aaroncox** [comment]
What sort of error message are you getting?

**Comment by twomoretoo11** [comment]
i dont recall but overtime a period of ten days i was able to send my eos
to my family's other account i believe i had to just wait a time of 10 day
i believe i could only make one move at a time like vote but not vote and 2
minutes later unstake eos , i hope this is not the reality i would like to
stake eos and vote and correct a vote all on the same day.... thank you for
your response thank you Aaron Cox...:)

**Comment by aaroncox** [comment]
So it sounds like it was a "Insufficient CPU" error? 

The network has been rather congested lately - so staking more CPU is the only solution at the moment. There are optimizations being made which, on the EOS network itself, which will hopefully make this better as time progresses.

In the mean time, there's always cpuemergency.com :)
