### ISSUE TITLE
Create account bug

### ISSUE THREAD

**Issue by cryptojoe10** [greymass/eos-voter#456]
![eos voter](https://user-images.githubusercontent.com/45642772/49884761-93a19f80-fe03-11e8-81f4-6c0d621aa64c.png)
After I fill out all the fields in the create account tool, the screen goes blank, making me unable to create an account.

**Comment by aaroncox** [comment]
Is this before or after hitting the submit button? I'm trying to reproduce the issue.

**Comment by cryptojoe10** [comment]
Before. 
I was able to get it to work by making sure my bytes was set above 2600.  Basically I wasn’t getting thrown the correct error with the bytes, so I didn’t know what I was doing wrong. 


Sent from Yahoo Mail for iPhone


On Thursday, December 13, 2018, 4:15 AM, Aaron Cox <notifications@github.com> wrote:


Is this before or after hitting the submit button? I'm trying to reproduce the issue.

**Comment by aaroncox** [comment]
Interesting - I'm still not able to reproduce for some reason. 

What version are you using and do you mind sharing the exact values you're attempting to use? 

![image](https://user-images.githubusercontent.com/677686/49967433-d4c3ad80-fef0-11e8-9946-67aa7bd448de.png)

**Comment by cryptojoe10** [comment]
Unable to recreate now! Sorry

**Comment by aaroncox** [comment]
All good, if you end up in a situation where you are, feel free to share those details! 

It might have also been a glitch in the API you were using or something, which would make it really hard to reproduce. Feel free to reopen if we find out additional info that could lead us to the bug.

**Comment by expertschoice** [comment]
I have the same issue with version 0.6.6 when trying to create a Worbli account. I get the greyscreen immediately when I put in any figure for RAM.  Have not resolved this yet.
