### ISSUE TITLE
0.6.4 EOS Account Wallet History Appears in Telos Account Wallet History

### ISSUE THREAD

**Issue by SonicAgamemnon** [greymass/eos-voter#471]
I have an account with the same name in both EOS and Telos networks.  When I switch from the EOS account to the Telos account and then look at its wallet history, I still see the EOS account history!

**Comment by dafuga** [comment]
I think this is fixed in the latest release, can you download it and let me know if you are still experiencing the issue? Thanks!

https://github.com/greymass/eos-voter/releases/tag/v0.6.5

**Comment by dafuga** [comment]
Closing out due to inactivity, feel free to open a new issue if the problem still exists.
