### ISSUE TITLE
Changing Owner and Active Public Keys to Ledger Keys Error

### ISSUE THREAD

**Issue by DiegoDDT** [greymass/eos-voter#473]
I sucsesfully changed my Owner and Active Public Keys to the one of my Nano Ledger, no the problem is that I cannot operate anymore with my account... I tried going to the Manage Wallets section and change my Hot wallet to a Ledger Wallet
![schermata 2018-12-19 alle 15 03 43](https://user-images.githubusercontent.com/23257667/50224937-70489880-039f-11e9-9cbf-7655eab2ec89.png)
I can see the message on the opened box: 
![schermata 2018-12-19 alle 14 58 36](https://user-images.githubusercontent.com/23257667/50224972-87878600-039f-11e9-99a8-7dde8da2b31c.png)
But where is the 'Modify account permissions' button to click???
At the end of the box I have this button:
![schermata 2018-12-19 alle 14 58 46](https://user-images.githubusercontent.com/23257667/50225101-df25f180-039f-11e9-9387-29abf97c9a97.png)
But it cannot be clicked...
What can I do? I cannot even cancel that account to re-import it...

**Comment by aaroncox** [comment]
With the information provided I'm not exactly sure what's going on.

Are there 2 different accounts in the screenshots above? You said you changed the account to use the Ledger, so what are you trying to convert now?

**Comment by aaroncox** [comment]
Found the problem, 0.6.6 will have the fix.
