### ISSUE TITLE
After Ledger setup: e.decorateAppAPIMethods is not a function

### ISSUE THREAD

**Issue by gbisaga** [greymass/eos-voter#487]
I just set up to use my Ledger Nano S, updated to latest EOS software (1.2.0). I switched over to use the Ledger for the Owner key, leaving the Genesis key as the Active key. Verified change on eosflare. Then I went to unstake some EOS:

1. Click Update staked EOS
2. Set both CPU and bandwidth to 5.000 EOS
3. Click update staked balances

Result: 
  Error
  e.decorateAppAPIMethods is not a function

Did not unstake the EOS (nothing is "Refunding")

**Comment by aaroncox** [comment]
This error typically means that the USB connection to the Ledger (the "transport" protocol) isn't communicating properly with the app. We've seen this reported a couple times now and have yet to find exactly what is causing it and haven't been able to reliably reproduce the issue. 

Here's a few things you can try:

- Close all apps that might be using the Ledger - some apps might grab ahold of the USB connection and prevent other apps from using it. Potentially even a reboot of the host computer.
- Close the app, unplug the Ledger, start the app back up again, and then plug the Ledger back in. This should try to reestablish the connection to the device.

Let me know if any of this works for you.

**Comment by aaroncox** [comment]
There is a log, it's location is dependent on the OS:

on Linux: ~/.config/eos-voter/log.log
on OS X: ~/Library/Logs/eos-voter/log.log
on Windows: %USERPROFILE%\AppData\Roaming\eos-voter\log.log

I haven't seen anything useful in the logs when trying to debug this in the past using them though. 

Few more questions: 

- Do you have any other accounts loaded up besides this one? 
- What version are you running at the moment?

If you happen to be running 0.6.5, and the only wallet you have loaded in is the Ledger wallet (meaning no other accounts loaded with keys), I'd be interested in seeing what the state of the wallet is from a fresh backup.

Under Tools -> Manage Wallets, there's a new "Backup" button that lets you save a JSON file, and within that file there will be entries for each individual wallet. For example, I have one for my ledger that looks like this:

```
    {
      "schema": "anchor.v1.wallet",
      "data": {
        "account": "developjesta",
        "authority": "owner",
        "chainId": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
        "path": "44'/194'/0'/0/0",
        "pubkey": "EOS6RWZ1CmDL4B6LdixuertnzxcRuUDac3NQspJEvMnebGcUwhvfX",
        "type": "ledger"
      }
    },
```

I'm curious to know if the `path` value in your currently non-functional wallet isn't being set properly. That's the only thing I can think of that the process is trying to `split` that could throw an error. Either that or perhaps the authority isn't being set properly.

**Comment by gbisaga** [comment]
I was using 0.6.4; just upgraded to 0.6.5, same problem. Here's my wallet export. I think this means I only have one.

    "wallets": [
        {
            "schema": "anchor.v1.wallet",
            "data": {
                "account": "gy4dkmjwhege",
                "authority": "owner",
                "chainId": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
                "path": "44'/194'/0'/0/0",
                "pubkey": "EOS8gZ6BoCdj6gvX3MPyWP1cENszDFubcgamVSpMvFLwmjFjHpYMo",
                "type": "ledger"
            }
        }
    ]

**Comment by aaroncox** [comment]
Alright, path looks good. I'm wondering if the path is being set incorrectly in the current wallet though. 

Try this:

- Tools -> Manage Wallets
- Click Import Account
- Click the Watch Wallet tab, and enter any account name (you can use `developjesta` or anything)
- Select one of the authorities and import the account.
- Switch to the new watch wallet, then switch back to your ledger wallet.

This swapping will force reload the currently active wallet, then try to perform an operation. If this fixes it, I think I know what the issue is and might be able to reproduce it.

**Comment by gbisaga** [comment]
Well, I don't know whether this is good news or bad news, but that worked. I just unstaked 10 EOS and it worked.

https://eosflare.io/account/gy4dkmjwhege

Hopefully that will give you a clue. If you'd like me to try anything else, I'm happy to oblige. Actually, I would not mind contributing to this effort. I'm very excited about EOS -I think crypto is going to have to get a lot more user-friendly for it to ever have mass adoption. I'm an architect/developer who uses NodeJS most of the time. Perhaps one way I could start is by writing documentation and then doing minor bug fixes/enhancements?

**Comment by aaroncox** [comment]
Hey sorry to fall off on this conversation. If you are interested in lending a hand with development, we should probably take the discussion to a better form of communication, perhaps email. Feel free to drop me a line through the email on my user profile.
