### ISSUE TITLE
AppImage does not work in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by alojzjakob** [greymass/eos-voter#49]
./eos-voter-0.1.5-x86_64.appimage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_eos-voY24qWr/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

**Comment by alojzjakob** [comment]
tried compiling myself, same error

**Comment by aaroncox** [comment]
It sounds like some sort of dependency is missing - `/browser/init.js` is internal to electron and should be bundled up with it. I'll do some research and see if I can come up with a solution.

**Comment by aaroncox** [comment]
I haven't tried this yet, but if you want: try changing the `electron-builder` version to `20.14.7`, running yarn's install again, and then compiling. It looks like this is a fairly recent issue and is being discussed in https://github.com/electron-userland/electron-builder/issues/2958.

**Comment by alojzjakob** [comment]
thanks!

didnt fix the issue with AppImage, but linux-unpacked release works ok, even with 20.15... just tried it :)

**Comment by alojzjakob** [comment]
closing since it is not critical and probably not the fault of the source code of thsi app
