### ISSUE TITLE
create new account bug

### ISSUE THREAD

**Issue by expertschoice** [greymass/eos-voter#520]
version 0.6.6 when trying to create a Worbli account. I get the greyscreen immediately when I put in any figure for RAM. Have not resolved this yet.

**Comment by aaroncox** [comment]
Thanks for the heads up, we'll look into it!

**Comment by dafuga** [comment]
So it turns out that Worbli doesn't allow you to buy RAM or create new accounts for now, so we will be deactivating both features in the next release. Thanks for bringing this to our attention @expertschoice !
