### ISSUE TITLE
Worbli account bug

### ISSUE THREAD

**Issue by expertschoice** [greymass/eos-voter#522]
Changing to a Worbli account (via the upper left drop-box) always opens in Locked mode, even though  settings are set to "disable automatic locking"

version 0.6.6

this does NOT happen when changing to EOS or TELOS.

**Comment by dafuga** [comment]
Is your Worbli account setup in hot mode? The app will always ask for your password when switching to a hot wallet regardless of the setting you mentioned (which allows you to lock the wallet automatically after a certain amount of time of inactivity).

**Comment by dafuga** [comment]
Closing out due to inactivity, feel free to open a new issue if the above comment doesn't help.
