### ISSUE TITLE
Handling of arrays/objects in the smart contract interface

### ISSUE THREAD

**Issue by aaroncox** [greymass/eos-voter#535]
Currently all inputs are either strings or integers, but some structs define values as arrays and eosjs actually expects an array. Simply writing a json representation of the array causes it to be misinterpreted. 

Example: 

![image](https://user-images.githubusercontent.com/677686/51219206-b987fb80-18fd-11e9-892c-ea19f1c03481.png)

The fields themselves need to be run through `JSON.parse` to build the array from the data, and the field itself potentially should be a multi-select dropdown with enterable values to allow easier usage.

The same logic should also be tested against the producer voting action, since I believe it requires the same types of input.

**Comment by lukestokes** [comment]
Left a comment here: https://github.com/greymass/eos-voter/pull/551/files#r259158141

**Comment by dafuga** [comment]
@aaroncox my understanding is that https://github.com/greymass/eos-voter/commit/3553e5304c7aa0aae3cfe13db3c47806e03d02d8 take care of the issue that Luke mentioned, is that correct?
