### ISSUE TITLE
Smart Contract is broken is some cases

### ISSUE THREAD

**Issue by szechem** [greymass/eos-voter#548]
If user is incorrectly filling form of action, it will cause infinity loading state on button. It is not possible to submit button again until restarting app.

**Comment by szechem** [comment]
![infinity_loop](https://user-images.githubusercontent.com/24317158/52062939-c3526580-2571-11e9-9cde-19294c9affa7.png)

**Comment by dafuga** [comment]
Hi @szechem , thanks for bringing this to our attention! It will be fixed in the next release (0.7.5).
