### ISSUE TITLE
Incorrect links to api explorer in app

### ISSUE THREAD

**Issue by szechem** [greymass/eos-voter#549]
In wallet -> history we can see some data with 'View Transaction' links. Clicking on one of them causes opening dialog with link including 'undefined'. It is not possible to find page in api explorer with such link.

**Comment by szechem** [comment]
![explorer](https://user-images.githubusercontent.com/24317158/52063138-496eac00-2572-11e9-99b3-57d0710a2343.png)

**Comment by dafuga** [comment]
Thanks for reporting this, it should be fixed when you download the latest version of the wallet.
