### ISSUE TITLE
Not Permission menu in the side pannel under Wallet Tool

### ISSUE THREAD

**Issue by Kinzowa** [greymass/eos-voter#580]
Hello, i installed the latest version of eos-voter 0.7.3 but i can't see the Permission menu in the side pannel under Wallet Tool. See screenshot https://imgur.com/l4wqdSF

What could be the reason?

Thank you

**Comment by Kinzowa** [comment]
It's OK after deleted Wallet credential.

**Comment by aaroncox** [comment]
It looks like you had done the 'Skip Import' and so there wasn't an account loaded yet. We hide a bunch of the tools that require an account if you don't have an account imported. Glad you got it working though and feel free to let us know if you run into any other problems!
