### ISSUE TITLE
Airdrops / Custom Tokens: cannot find or add DAPP token?

### ISSUE THREAD

**Issue by bracklanna** [greymass/eos-voter#583]
in eos-voter v.0.7.4 under macOS Mojave 10.14.3:

Under "Airdrops / Custom Tokens," doing "Scan Balance" does not locate Liquidapps.io's  `DAPP` tokens even though same have been transferred to the account from the LiquidApps `instanttrack` token distribution contract. 

When attempting to do a manual "Add Custom Token", entering `DAPP` in the "Contract Asset Symbol" input box gives the result, "Token Not Found: The details for the token entered could not be found."

Any insight into why the DAPP token doesn't show up?

**Comment by aaroncox** [comment]
It looks like the contract is actually `dappservices` with the symbol of `DAPP`. 

I'm not sure what the `instanttrack` contract is doing, but it doesn't look like a standard token contract.

**Comment by bracklanna** [comment]
Thanks. This "issue" was UFRM (user failure to read manual,) it can safely be closed and/or deleted entirely.

**Comment by aaroncox** [comment]
Hah, no worries at all. I had to do some investigation to figure it out as well!
