### ISSUE TITLE
delegate not responding

### ISSUE THREAD

**Issue by S3M420** [greymass/eos-voter#584]
I am trying to unstake EOS i have staked to another account.  When i click confirm, the window does nothing with the circle spinning icon forever.  I tried to delegate EOS just to see, and it does the same thing.

**Comment by aaroncox** [comment]
Hrm, does the account you're using have enough staked EOS to perform these actions? I just did some tests and they seemed to work on my end.

There may be an error message if you go into View -> Toggle Dev Tools, and then go look at the console tab of that area. It'd be red text that would appear when you perform the action and the circle spins forever.

**Comment by aaroncox** [comment]
Also what version?

**Comment by S3M420** [comment]
![Screenshot from 2019-03-22 15-11-27](https://user-images.githubusercontent.com/48839600/54850303-d1407f00-4cb4-11e9-9382-d875009318dd.png)

version 0.7.4

**Comment by S3M420** [comment]
trying to find how to change nodes... maybe that's the issue

**Comment by S3M420** [comment]
yup... that was the issue.  back on ole trusty greymass node.  don't remember why i swapped... Thanks for pointing out the console to me!  Maybe i can self diagnose any issues in the future.
