### ISSUE TITLE
Integration with Insights blockchain -- unable to transfer to INSTAR

### ISSUE THREAD

**Issue by darwinrlo** [greymass/eos-voter#598]
Below, "dev" refers to program that is started by running `npm run dev` on the commit tagged with `0.7.6`. "Production" refers to the program that is installed using the installer.

Unlock a wallet. Observe:
* Balances in Wallet
  * Development: Liquid is 3.0000 INSTAR [correct]
  * Production: Liquid is 0.0000 EOS [incorrect]
* Staked INSTAR in Wallet
  * Development: Total for both CPU and Network are 0.0001 INSTAR [correct]. Delegated is 0.0001 EOS for both CPU and Network [incorrect].
  * Production: same as dev

Try transferring tokens:
* Click Send Tokens. A modal titled Transfer Tokens pops up.
  * Development:  Says, "3.0000 INSTAR available to transfer." [correct]
  * Production: Says, "0.0000 EOS available to transfer." [incorrect]
* Enter a destination account.
* The Token Selection pulldown menu shows, "No results found." [Expected: `INSTAR` is shown as one of the options.]
* Enter a quantity:
  * Development: "3.0000 INSTAR available to transfer" changes to "0.0000 EOS available to transfer." [incorrect]
* Enter a Transfer Memo and click Confirm.
  * Development: Quantity is `1.0000 EOS ()`. [Expected: The quantity is shown as `1.0000 EOS (eosio.token)`.]
  * Production: Quantity is `1.0000 EOS (eosio.token)` [Expected: INSTAR instead of EOS]
* The error from proceeding:
  * Development: `contracts<string|array>, transaction<callback|object>, [options], [callback]`
  * Production:
    ```
    {
      "code": 500,
      "message": "Internal Service Error",
      "error": {
          "code": 3050003,
          "name": "eosio_assert_message_exception",
          "what": "eosio_assert_message assertion failure",
          "details": []
      }
    }
    ```

**Comment by aaroncox** [comment]
Thanks for the heads up - not sure what happened but we'll get this resolved.

**Comment by aaroncox** [comment]
We did some digging and weren't able to reproduce, I'm wondering if maybe the local state the wallet got corrupted somehow during prior development/setup you may have done? Does the problem persist if either:

- Reset via Tools -> Reset Application
- Remove the local electron files, located:
  - `%APPDATA%/Electron` on Windows
  - `$XDG_CONFIG_HOME` or `~/.config` on Linux
  - `~/Library/Application Support/Electron` on macOS

The above paths are for when running via `npm run dev`, and the production build would be in the `eos-voter` folder in the same paths instead of `Electron`.

**Comment by darwinrlo** [comment]
That improved the situation but there are still behaviors that deviate from expected behavior. As of deleting `~/Library/Application Support/eos-voter`, the following now behaves as expected:

* Balances in Wallet: Liquid is 10.0000 INSTAR [I'm using a different account.]
* Staked INSTAR in Wallet: Delegated is now showing 0.0001 INSTAR for both CPU and network bandwidth. As before, the staked amounts for CPU and network bandwidth are both shown as 0.0001 INSTAR.

However, in the Transfer Tokens model, which pops up as a result of clicking the Send Tokens button:
* It correctly shows, "10.0000 INSTAR available to transfer." But upon entering a quantity, it changes to "0.0000 EOS available to transfer." Furthermore, INSTAR does not appear as a possible Token Selection.

**Comment by aaroncox** [comment]
@dafuga has been working on reproducing this and addressing the issue, and I believe we've made a bit of progress. PRs #600 and #601 were both merged into our `develop` branch over the last day or so and from what he's reported, it seems to resolve the issues. We'll continue to test - feel free to try them out yourself as well, and we'll get them added in a 0.7.7 release with the fixes.

**Comment by darwinrlo** [comment]
I was able to give it a whirl... and it works now! Thanks for making the fixes.

**Comment by aaroncox** [comment]
No problem at all - will close this out 👍
