### ISSUE TITLE
429 Error at Authorize

### ISSUE THREAD

**Issue by BenCook28** [greymass/eos-voter#602]
I first installed my EOS Voter wallet in Sept. 2018, and then tried to log back in on Apr. 4, 2019.  I got errors at the server page, so I upgraded to version 0.7.6 and got to the authorize page.  I then inspected the page with Chrome developer tools and saw 429 errors as shown in the attachment.
<img width="549" alt="Screen Shot 2019-04-14 at 3 22 17 PM" src="https://user-images.githubusercontent.com/27933795/56098048-0dd55400-5eca-11e9-81df-56a1de6e6399.png">

**Comment by aaroncox** [comment]
429 is "too many requests", so from the sounds of it, EOSNY is rate limiting their API preventing those requests from completing. 

Try changing the node to one that doesn't rate limit - you're free to use ours at https://eos.greymass.com

**Comment by BenCook28** [comment]
Thank you for your help and quick reply, Aaron
