### ISSUE TITLE
Update 0.7.6 changed my wallet name to have "@owner" on the end

### ISSUE THREAD

**Issue by JohnAlf** [greymass/eos-voter#604]
I am using a Watch wallet (desktop) and Owner on an airgap. After the last update 0.7.6 the wallet name on the Watch wallet changed from {myname} to {myname}@owner. Now when I try to sign something the airgap gives me the error message, "The unsigned transaction loaded does not match the current wallet. Either switch to the proper wallet or import the keys for {myname}@owner"
(I had not updated in many months)

**Comment by aaroncox** [comment]
On the cold wallet interface - does it say {myname}@**owner** or {myname}@**active**, or neither and just {myname}?

The suffix after the **@** needs to match on both the watch/cold wallet interfaces due to how the transactions are being generated.

**Comment by JohnAlf** [comment]
neither. it just says my wallet name with no @ extension

Sent with Protonmail.com encrypted/secure email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by aaroncox** [comment]
Alright - that makes sense as to why it's not signing properly. It sounds like your cold wallet failed to update its own data properly in one of the steps during the upgrade process. We actually built a UI element to detect and help users update this data manually, but there's another bug preventing that UI from appearing in the most recent build. 

We have a few things to fix here.

In the mean time, you should be able to resolve the issue on the Cold Wallet itself by just setting it up again. Assuming you also have the private keys on the offline device (or access to them), you should just be able to click the Greymass logo in the upper right, scroll to the bottom, and reset the application. From there you can import the keys again, and select the proper permission (**@extension**) as you're setting up again. 

That should get you signing now should you need it. Let me know if you run into any problems with that.

**Comment by JohnAlf** [comment]
so when I set it up again, on the airgap, it should say {myname}@owner, right?
No way to just add another wallet name to the airgap?

**Comment by JohnAlf** [comment]
Thanks for your help, Aaron. I am back up now. Much appreciated. ;)

**Comment by JohnAlf** [comment]
Thanks for your help, Aaron. I am back up now. Much appreciated. ;)
