### ISSUE TITLE
Air drop Owner won't verify PEOS airgrab

### ISSUE THREAD

**Issue by JohnAlf** [greymass/eos-voter#605]
Have been signing with no problems (recently) when signing a proxy and unstaking tokens. Just tried to claim the PEOS airgrab. It saved the unsigned transaction to disk ok. When I loaded it into the airdrop computer it showed normally, showing 55 minutes left with 1 transaction and 1 action. When I clicked on Sign This Transaction, the button acted normal when it changed color as I clicked it, but it did not sign it. Tried it several times. Unable

**Comment by aaroncox** [comment]
I was able to reproduce this issue and find a fix for it. What was happing was the contract's code wasn't being included in the file being saved, so the cold wallet wasn't able to sign it properly. 

We'll get this fix bundled up into 0.7.7 - and you should only have to upgrade the watch wallet (not cold) in order for newly generated unsigned transactions to be sign-able by a 0.7.6 cold wallet.

**Comment by JohnAlf** [comment]
Thanks, Aaron ;)

Sent with Protonmail.com encrypted/secure email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
