### ISSUE TITLE
Convert Account to use Ledger Hardware

### ISSUE THREAD

**Issue by BillioniresMind** [greymass/eos-voter#623]
Hi,

Been trying to convert my account to use Ledger Hardware, but it has gotten to the screen where it says "Awaiting Key Change" and this has stayed on for almost an hour. 

I have quit the app, restarted it again and it stays on the same page without any change. Is this normal?

Regards.
![eos voter](https://user-images.githubusercontent.com/39076539/57068162-d1c33100-6cc8-11e9-8ee5-8bd577d66f01.png)

**Comment by aaroncox** [comment]
From the sounds of it - it looks like the transaction to update your permissions might have failed?

One way to manually fix this would be to take the "Public Key of Ledger" field, and manually update your account permissions to match that key. This is what this process does in the background, but you can do it manually with the following steps:

- Select the account and unlock the wallet.
- Go into Tools -> Permissions.
- Click on the "Modify" button for the permission you want to modify (which looks to be `active` from the above screenshot). 
- Paste the "Public Key of Ledger" that would be shown in the screenshot you pasted above.
- Click "Update Permission" to submit the change to the account.

Then, if you go back to the upgrade process, it should detect the new public key and let you proceed.

**Comment by BillioniresMind** [comment]
Hi Aaron,

I've followed your exact instructions and I get an error. I've attached an image.

Regards.
![update permission error 2](https://user-images.githubusercontent.com/39076539/57118491-8f96ff80-6d5b-11e9-93b8-e7756c7aa57e.png)
![update permission error](https://user-images.githubusercontent.com/39076539/57118492-8f96ff80-6d5b-11e9-8e61-68acaa58f9db.png)

**Comment by aaroncox** [comment]
When looking at the permissions screen, does the "Currently used key" match the "active key", like so:

![image](https://user-images.githubusercontent.com/677686/57118549-09b28e80-6d32-11e9-9ed7-f80cafc03466.png)

If they don't match - then it sounds like either the wrong key is loaded into the app (maybe it was changed at some point) or there's a bug preventing it from being loaded properly.

**Comment by BillioniresMind** [comment]
Hi Aaron,

The "Currently used key" matches the "active key"...

![update permission error 3](https://user-images.githubusercontent.com/39076539/57119122-bfe09d00-6d5f-11e9-80ca-8f1d5f726c71.png)

**Comment by aaroncox** [comment]
Huh - interesting, sounds like the wallet must have entered an invalid state somehow.

The easiest way to try and fix that is just to reimport the wallet again. If you have more than one account, swap off it and delete the buggy account, and re-add it; or you can reset the wallet (Tools -> Reset Application) and then resetup the entire thing from scratch. Another option would be to reset and restore a backup if you've got one. 

We had a few issues with how wallets were being upgraded from version to version in the past, this sounds like one of them. The new version of the app we're working on we took the time to completely rewrite how our wallet storage system works and we're hopeful that it'll put an end to these weird bugs.

**Comment by BillioniresMind** [comment]
Hi Aaron,

Thanks for your help. I imported the private key on a new computer and it seems to have worked.

Thanks and stay blessed.

**Comment by aaroncox** [comment]
Glad to hear it! This issue seems to be popping up more than normal around this release, but glad we found a solution.
