### ISSUE TITLE
REX Deposit not working

### ISSUE THREAD

**Issue by hyfong8687** [greymass/eos-voter#656]
When I tried to deposit funds to REX with Ledger Connected, I received the following ERROR messages:

1. Invalid data received (0x6a80); or
2. Cannot write to HID  device.

What should I do? Please advise.

**Comment by aaroncox** [comment]
You'll have to go into the settings on the Ledger device itself and enable "Arbitrary Data". The ABI stored within the EOS app running on the device doesn't know what REX is yet, so it needs to use this feature in order to sign the transactions.

**Comment by hyfong8687** [comment]
My Ledger settings have only shown "Contract data" which ask me to "Allow contact data in transactions or NOT Allowed".

How should I proceed? Please advise.

**Comment by aaroncox** [comment]
Hrm, maybe there's a new update that changed what it says. That sounds right though, try enabling that and then trying to perform a REX action.

**Comment by hyfong8687** [comment]
I Just pressed "Allow contract data in transactions", it worked and I could deposit funds in REX. Thank you.
