### ISSUE TITLE
error_transactions must have at least one authorization

### ISSUE THREAD

**Issue by johnnykabro** [greymass/eos-voter#660]
Hi guys 
I have an issue with my grey mass wallet
I am trying to send EOS to another of my accounts and no matter what I try to send out of grey mass either 1 or 150 I keep getting the same result.... error_transaction must have at least one authorization 
I was in the middle of trying to persuade a non-crypto civilian over and this happens to me not a good look for crypto work flow.

**Comment by aaroncox** [comment]
From the sounds of it - the wallet itself is missing some information, we've seen this during upgrades of the app from time to time.

The easiest way to get around this right now is just reimporting your wallet/keys. 

Before you go further, make sure you have your private keys saved someplace safe! You can retrieve them via the Tools -> Manage Wallets, by viewing the wallet's data.

Then go into Tools -> Reset Application, which will completely wipe the local wallet data, and then run through the setup process. 9/10 times, this will then have the wallet working moving forward.

Let me know if that doesn't fix it for you.

**Comment by johnnykabro** [comment]
Omg
thanks for your help but I am a novice at this and I have a bunch of airdrops and I really dont want to lose everything for a simple maybe mistake what do you recommend I do....?

**Comment by aaroncox** [comment]
Resetting EOS-voter and reimporting your keys won’t impact your account balances and airdrops. Your account exists on the blockchain, and the balances are associated to the account - your wallet is just an app that lets you access the account on the blockchain.

**Comment by johnnykabro** [comment]
oh okay thank you very much I will try it now

**Comment by dafuga** [comment]
Are you still experiencing the issue?
