### ISSUE TITLE
WAX: Claim GBM Rewards

### ISSUE THREAD

**Issue by aaroncox** [greymass/eos-voter#675]
We should add a WAX-only button for claiming GBM rewards.

https://wax.bloks.io/wallet/gbm-rewards

The button should be added to the wallet tab (under Update Staked Amounts), if the account is a genesis account. Labeled "Claim GBM Rewards" on the button.

Query showing how to determine if something is a genesis account:

https://wax.bloks.io/account/eosio?loadContract=true&tab=Tables&table=genesis&account=eosio&scope=wu45y.waa&limit=100

The button when clicked should create/sign/broadcast an action from the `eosio` contract named `claimgbmvote`, with the `owner` parameter set to the current account name. It should also do the same and run the `claimgenesis` action on the `eosio` contract with the same parameters.

Both of these actions can be bundled into one transaction like create account.

https://wax.bloks.io/account/eosio?loadContract=true&tab=Actions&table=genesis&account=eosio&scope=wu45y.waa&limit=100&action=claimgbmvote

Example TX on live:

https://wax.bloks.io/transaction/f891849ae94b7b46bd66d3a5237eeeb06e95be25b1c1d673c3b881f1987b5c7f

**Comment by dafuga** [comment]
This has been merged into develop and will be in the next release.
