### ISSUE TITLE
Where is Privatekey in Backup

### ISSUE THREAD

**Issue by meshfields** [greymass/eos-voter#696]
I am using the new backup feature for the wallet and when looking at the JSON I only see the PubKey. Is there a way to get to my original private key in clear text? Thanks

**Comment by aaroncox** [comment]
Which version specifically, one of the 0.7.x versions? If so, it's encrypted within the `wallets.data.data` field with AES256 encryption using your password. We don't ever store the keys themselves in plain text.

If you are just looking to get the private key out, I'd probably recommend using eos-voter to get them out. 

- Select the account you want to get the private key for.
- Unlock that wallet.
- Go into Tools -> Manage Wallets
- Click the right button on the row of the account you are interested in.
- Click "View Wallet"
- The UI will show the information about the wallet, as well as a "Private Key" field. Click the checkbox below the private key of "Show Private Key", and it will be displayed in the text box unencrypted.

**Comment by meshfields** [comment]
There is not Privatekey Field, only Public.

**Comment by aaroncox** [comment]
The Private Key field will only appear if:

- You are using that wallet
- The wallet is unlocked
- It is a hot wallet, not a ledger/watch wallet
