### ISSUE TITLE
Unstaking seems broken when using a watch wallet.

### ISSUE THREAD

**Issue by dafuga** [greymass/eos-voter#707]

**Comment by dafuga** [comment]
<img width="1480" alt="Screen Shot 2019-10-23 at 12 09 19 PM" src="https://user-images.githubusercontent.com/16295163/67353697-2a93c800-f58e-11e9-9b26-4ee5b837d25a.png">

**Comment by aaroncox** [comment]
Good catch - I wonder why those aren't trying to prompt for a download.
