### ISSUE TITLE
Voting on proposals breaks when using watch wallet

### ISSUE THREAD

**Issue by dafuga** [greymass/eos-voter#709]

**Comment by dafuga** [comment]
<img width="1180" alt="Screen Shot 2019-10-24 at 3 37 02 PM" src="https://user-images.githubusercontent.com/16295163/67460034-f6df9d80-f674-11e9-95f6-0a45f18787a5.png">

**Comment by aaroncox** [comment]
![image](https://user-images.githubusercontent.com/677686/67969822-5e9b6880-fbe0-11e9-88e2-62fd2d9f9a00.png)

The actual error, it's related to this having a bad proposal name.

If you try voting on a different proposal it works fine.

![image](https://user-images.githubusercontent.com/677686/67969864-6e1ab180-fbe0-11e9-97d1-2cab044ba342.png)
