### ISSUE TITLE
Smart contract contract search is broken.

### ISSUE THREAD

**Issue by dafuga** [greymass/eos-voter#710]
Unable to type anything in the contract search bar.

**Comment by dafuga** [comment]
![smart_contract_section_bug](https://user-images.githubusercontent.com/16295163/67574461-75bbff80-f775-11e9-9597-b74d81a0403f.gif)

**Comment by dafuga** [comment]
![smart_contract_section_bug](https://user-images.githubusercontent.com/16295163/67574676-db0ff080-f775-11e9-964a-b8a067467769.gif)

**Comment by aaroncox** [comment]
Did this start working or something?
