### ISSUE TITLE
Resource page just loads forever

### ISSUE THREAD

**Issue by dafuga** [greymass/eos-voter#711]
Will comment if I figure out how to reproduce.

**Comment by dafuga** [comment]
![resource_page_just_loads](https://user-images.githubusercontent.com/16295163/67575848-64282700-f778-11e9-8f5a-639f97c55c1c.gif)

**Comment by dafuga** [comment]
I think it happens when a single watch wallet is loaded.

**Comment by dafuga** [comment]
<img width="1182" alt="Screen Shot 2019-10-25 at 11 16 04 PM" src="https://user-images.githubusercontent.com/16295163/67578492-840e1980-f77d-11e9-8238-f477ab897a11.png">
I think this is related to the above issue, but the wallet page doesn't load either.

**Comment by aaroncox** [comment]
Yep, odd. I'm able to reproduce. We'll get this fixed.

**Comment by aaroncox** [comment]
![image](https://user-images.githubusercontent.com/677686/67601657-e4339a00-f742-11e9-999c-e76363b6fa30.png)

Looks like it was timing out - our APIs are apparently being slower than 3 seconds. I'm increasing it to 10 seconds.

**Comment by aaroncox** [comment]
I've disabled our `get_currency_balances` enhancements until we can optimize it, and it resolved the issue.
