### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by cryptojoe10** [greymass/eos-voter#723]
when i click the login . button after i enter my password. there is no response,  i tried to update to the most recent version. no luck .  help?

**Comment by aaroncox** [comment]
You mean when you're unlocking your wallet? An error should appear, but if it doesn't it typically means the password wasn't recognized for some reason. Are you sure you're using the right password? 

Mind providing some more information, like which screen you were trying to unlock from? Maybe a screenshot to show us where you're at in the process?

If all else fails and you need to reset your password (and you have your private keys backed up safely), you can always reset the application (Tools -> Reset Application), and then set it up again using a new password. You'll go through the process of reimporting your keys/accounts again which can be a hassle, but it's really the only way to re-establish a new wallet when the password goes bad.

**Comment by aaroncox** [comment]
Closing old issue, please reopen if the problem persists.
