### ISSUE TITLE
Disconnected UI "Edit" button doesn't redirect properly

### ISSUE THREAD

**Issue by aaroncox** [greymass/eos-voter#729]
When blockchain node is unreachable and no accounts, clicking the exclamation mark then edit blockchain just closes the dialog, and the blockchain and name is wrong.

<img width="1204" alt="Screen Shot 2019-11-05 at 00 04 50" src="https://user-images.githubusercontent.com/677686/68166119-4fddea00-ff2f-11e9-8e53-016dbb788f4a.png">

<img width="1204" alt="Screen Shot 2019-11-05 at 00 04 55" src="https://user-images.githubusercontent.com/677686/68166118-4fddea00-ff2f-11e9-800f-d47f60c38c23.png">

**Comment by dafuga** [comment]
This seems to be working fine on latest release version.
