### ISSUE TITLE
Check for update function

### ISSUE THREAD

**Issue by volschin** [greymass/eos-voter#73]
To not leave the installation on an old release, it would be helpful to show the user automatically if a new version ist availabe. It should be possibe to disable this check.

**Comment by aaroncox** [comment]
I think we may go so far as to make it a manual action, in that you have to force an update check. 

One of the principals we have while working on this tool is that it shouldn't connect to any resource unless you ask it to.

**Comment by aaroncox** [comment]
Added in 0.2.0 - with a big warning about security and a checkbox to ensure users understand the risks involved.
