### ISSUE TITLE
Getting error when trying to broadcast transaction

### ISSUE THREAD

**Issue by dafuga** [greymass/eos-voter#736]
<img width="1179" alt="Screen Shot 2019-11-19 at 2 22 20 PM" src="https://user-images.githubusercontent.com/16295163/69118853-2d73d100-0ad8-11ea-903b-a0673af4973a.png">

**Comment by aaroncox** [comment]
Looks like the `setTransaction` action isn't being imported into the container that's trying to call that.

**Comment by dafuga** [comment]
This was being cause by redux rehydration and is not an issue on the released version of the wallet.
