### ISSUE TITLE
Sending EOS results in expired transaction

### ISSUE THREAD

**Issue by karbica** [greymass/eos-voter#738]
I have 10 CPU and 1 NET staked and I cannot transfer my EOS to another account.

```json
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3040005,
    "name": "expired_tx_exception",
    "what": "Expired Transaction",
    "details": [
      {
        "message": "expired transaction f70ad50d7a73e32967b2073b68418a17fe69de9e8e1f6d5fae09a54abbef287d",
        "file": "producer_plugin.cpp",
        "line_number": 470,
        "method": "process_incoming_transaction_async"
      }
    ]
  }
}
```

<img width="1276" alt="Screen Shot 2019-11-21 at 3 32 33 AM" src="https://user-images.githubusercontent.com/8563742/69334487-acb7f080-0c0f-11ea-96ef-1b9af8af64a4.png">

Is there something going on with the network?

I appreciate any help.

**Comment by aaroncox** [comment]
Sorry for the delay! 

That's an odd error to be getting. Are you using a cold/watch wallet or just a normal wallet?

Transactions I believe are naturally set for 1 minute expiration, so you should be hitting it. Another thing I suppose would be good to check is your systems clock, make sure that's synced up properly and has the current date/time.

**Comment by karbica** [comment]
@aaroncox Thanks for the response. I'm using a normal wallet, one that was created during the genesis.

I'm running this wallet on a 2017 MacBook. The time settings are synced by Apple's services. Could this be an issue with the amount of the CPU/NET I have staked? I consistently hit this limit all the time. Are there any alternatives I can use for a workaround?

Thanks for taking the time to attend to my issue.

**Comment by aaroncox** [comment]
If it were related to CPU/NET, I'd expect a different error message. 

I'm not entirely sure why it'd be reporting expired - which API node are you using to submit the tx, the default? I did some tests on my end just to make sure and I can't seem to replicate this issue. 

Very odd indeed!

**Comment by karbica** [comment]
Where can I find which API node I'm connected to? And could you give me the one you are using? I'll try and change that and see if that works.

Thanks!

**Comment by aaroncox** [comment]
You can change them for each blockchain under Tools -> Manage Blockchains. There's a dropdown on the far right of each row that'll let you edit that blockchains configuration. 

The area you can edit the API node is located there. 

I'm using the Greymass nodes here: https://eos.greymass.com

Is the error still occurring regularly for you?

**Comment by karbica** [comment]
Thanks for that, I am using that API as well.

I attempted to make another transaction but received a different error this time.

```json
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3080004,
    "name": "tx_cpu_usage_exceeded",
    "what": "Transaction exceeded the current CPU usage limit imposed on the transaction",
    "details": [
      {
        "message": "billed CPU time (694 us) is greater than the maximum billable CPU time for the transaction (9 us)",
        "file": "transaction_context.cpp",
        "line_number": 553,
        "method": "validate_cpu_usage_to_bill"
      }
    ]
  }
}
```

Is this because I have not staked enough CPU/NET? I have 5 CPU and 1 Bandwidth.

**Comment by aaroncox** [comment]
Sorry for not getting back to you on this one, I just discovered this conversation again while closing out old issues.

Yes, the new error means you don't have enough staked. If you need further help, feel free to open a new issue or join us on telegram https://t.me/greymass
