### ISSUE TITLE
Transaction success message is in some cases either missing tx id and/or is not clickable

### ISSUE THREAD

**Issue by dafuga** [greymass/eos-voter#748]
<img width="938" alt="Screen Shot 2019-12-17 at 3 34 53 PM" src="https://user-images.githubusercontent.com/16295163/70972531-ee409c00-20e6-11ea-94f6-143f65583e0e.png">

**Comment by aaroncox** [comment]
We need a way to reliably reproduce this so we can deal with it. I haven't seen one in a while though.

**Comment by dafuga** [comment]
I haven't seen this issue in a while so will go ahead close the issue for now, but we can reopen if ever we see it again.
