### ISSUE TITLE
Resource page doesn't load properly after switching between blockchains.

### ISSUE THREAD

**Issue by dafuga** [greymass/eos-voter#749]
Issue happens when jumping between EOS and Jungle.

<img width="940" alt="Screen Shot 2019-12-17 at 4 51 08 PM" src="https://user-images.githubusercontent.com/16295163/70975709-c9035c00-20ed-11ea-9d05-74f2ca806d9d.png">

**Comment by dafuga** [comment]
<img width="948" alt="Screen Shot 2019-12-17 at 4 55 27 PM" src="https://user-images.githubusercontent.com/16295163/70975840-15e73280-20ee-11ea-9a32-ec9cae8a64f6.png">
Probably related to this error, it seems that the app is trying to lookup the old account on the new node which is returning a 500.

**Comment by aaroncox** [comment]
@dafuga You have to use `fixes` I think on your commits to automatically close these 😁
