### ISSUE TITLE
Can only set one array at a time on smart contract interface.

### ISSUE THREAD

**Issue by dafuga** [greymass/eos-voter#758]
![only_one_array_in_smart_contract_form](https://user-images.githubusercontent.com/16295163/71767243-77f8c200-2f4d-11ea-8b35-60158dca2964.gif)

**Comment by aaroncox** [comment]
Mind sharing the contract and action so I can reproduce? 😆

**Comment by dafuga** [comment]
I think it does it for any contract action with two arrays. When I tested this I was using a custom action on my local nodeos instance so I would have to deploy that contract to jungle for you to be able to use it. I can do so if you want, but it might be simpler if I just look into the issue on my side. 😄
