### ISSUE TITLE
When voting on activated chain the wallet doesn't work still consuming CPU

### ISSUE THREAD

**Issue by Gutalean** [greymass/eos-voter#76]
I have Linux Mint. After I submit a transaction with my votes the screen gets grey/frozen and nothing happens. No transactions go to the mainnet.

**Comment by aaroncox** [comment]
Have you referenced an external block explorer to check for those transactions?

We noticed some of the tx id handling throws an error at times, which is what causes that black screen to display, but most likely the transactions did complete.

**Comment by aaroncox** [comment]
Closing this as newer versions should have resolved this bug.
