### ISSUE TITLE
Eos Tokens missing after being unstaked

### ISSUE THREAD

**Issue by JCassidy42** [greymass/eos-voter#77]
due to all but ten tokens starting out staked i tried to unstake the majority of mine but when doing so the tokens just vanished they are not accounterd for in wallet as staked or unstaked and i can not find any referance to them at all it just seems as if my 120 sumthing tokens vanished _

**Comment by aaroncox** [comment]
The APIs themselves are not returning the staked balance - we're investigating. 

If you view your account on a working block explorer, you should be able to see those values.

**Comment by Concorde89** [comment]
You should be able to see you tx on https://eosmonitor.io
Check the details and you will see your unstaked eos.
Wait 72 h.
Good luck.

**Comment by aaroncox** [comment]
These balances will now be displayed in the UI as of v0.1.6.
