### ISSUE TITLE
CPU에러

### ISSUE THREAD

**Issue by jhwi** [greymass/eos-voter#776]
!
![에러](https://user-images.githubusercontent.com/60065054/72681841-c5a72a00-3b0a-11ea-96d4-d394815b71b2.PNG)

**Comment by dafuga** [comment]
It seems that you do not have enough CPU to carry out the transaction. Are you using Anchor or Eos Voter? If you download the latest version of our Anchor app (https://github.com/greymass/eos-voter/releases/tag/v1.0.0-rc5), you can enable Greymass Fuel which will give you access to enough CPU for that transaction. Once on Anchor, just put your cursor over the brain logo in the top right corner and then click on `Enable Fuel`. Once that's done, you can retry the transaction and it should go through.
<img width="1152" alt="Screen Shot 2020-01-19 at 10 54 22 PM" src="https://user-images.githubusercontent.com/16295163/72682313-1a4ca400-3b0f-11ea-8547-8d54d922cd19.png">

**Comment by dafuga** [comment]
Closing this, but feel free to reach out again if you have more questions.
