### ISSUE TITLE
So how to get by "Transaction exceeded the current CPU uage limit..."?

### ISSUE THREAD

**Issue by kenw232** [greymass/eos-voter#809]
What does someone have to do to fix this?  I try to add/stake/buy more CPU but I still get the same error?  It could not be more god damn stupid.  I actually can't access my EOS now.  Its locked in this stupid restriction.  How does this nonsense happen?

![screenshot_001](https://user-images.githubusercontent.com/2769690/76994694-2c876a80-6925-11ea-9162-4e9fa15cf7a0.jpg)

**Comment by aaroncox** [comment]
It is pretty frustrating right now for many. The 907us in the error message represents about 9 EOS staked worth of CPU you'd need to complete the transaction. 

Staking more EOS would work, but you'd need to stake enough to perform the staking operation itself. Staking 1 or 2 wouldn't work, you'd need to stake 10-20 to complete the staking operation. Then you'd be able to perform 1-2 transactions every 24 hours or so. For my minimally used accounts, I tend to have 50-100 EOS staked to CPU at this point. 

On the flip side - there are a number of wallets/services now that will cover some resource costs for you if you don't want to stake yourself. Our newer wallet, Anchor, also offers this. I'm assuming this error message was for eos-voter, which does not offer covering resource costs. 

Few options for you if you're not interested in staking more:

- Upgrade to our new wallet, Anchor. You can download it from [this repository](https://github.com/greymass/eos-voter/releases/tag/v1.0.0-rc7) (which will be renamed). If you'd like more information, you can also [check out our blog](https://greymass.com/en/blog/5ms-worth-of-free-transactions-available-now-in-anchor-wallet/).
- If you're a Scatter user, you can use EOSAuthority.com or bloks.io, both of which provide options to cover the resource costs of a few transactions per day.

**Comment by kenw232** [comment]
Yes it was from eos-voter.  can I switch wallets?  Like export my public/private keys from eos-voter and import into Anchor?  I'd see my EOS tokens from the eos-voter wallet in Anchor?  is that thing?

**Comment by aaroncox** [comment]
Yep, you sure can. The two applications can be installed side by side and run at the same time, and you can save a backup from eos-voter and then restore it during the Anchor setup process. 

Here's a guide we wrote recently with the step-by-step instructions:

https://greymass.com/en/blog/migrating-to-anchor-from-eos-voter-greymass-wallet/

**Comment by kenw232** [comment]
I did it, migrate and Anchor was great.  But I see no Fuel icon.  How do I get Fuel to work?  My default node is "https://eos.greymass.com".

**Comment by aaroncox** [comment]
Which version of Anchor did you install? 

One other shot in the dark to get the icon to appear - try restarting Anchor.

**Comment by kenw232** [comment]
Ok, got Fuel to enable.  Using version 1.0.0-rc7.  I tried to send EOS and still get the "This account has exceeded its usage quota for the specified amount of time." with Fuel enabled.  Any idea?  Never seen a bigger nightmare just trying to send some tokens.

**Comment by kenw232** [comment]
I see it worked.  Fuel allowed me to stake for CPU.  thats all I needed to do.

**Comment by aaroncox** [comment]
Yeah - the situation isn't great, with the requirement of staked tokens being so high right now. 

I'll look into why you may have gotten that error, that's something we can improve on our side. Glad you were able to get some staked!
