### ISSUE TITLE
TRANSFER COIN ISSUE

### ISSUE THREAD

**Issue by KingArthur111** [greymass/eos-voter#810]
Hello,
I've tried to transfer my EOS tokens to Binane through the EOS voter version 0.7.12 on windows chrome through actove or owner account of transfering tokens with ledger right before it finsihes I get a message below

{"code".500,"message"."Internal Service Error","error".{"code".3100008,"name"."unsupported_feature","what"."Feature is currently unsupported","details".[{"message"."Returning WAST from get_code is no longer supported","file"."chain_plugin.cpp","line_number".1538,"method"."get_code"}]}}png)

Please let me get how to resolve this error.

Thanks in advance.

**Comment by aaroncox** [comment]
Which API node are you connected to, have you changed it from https://eos.greymass.com?

**Comment by KingArthur111** [comment]
I added to CPU and it was processed

**Comment by aaroncox** [comment]
Alright awesome, glad you got it resolved. I'll close this issue out. Feel free to open a new one should you run into this issue again!
