### ISSUE TITLE
Awesome work guys, would you like someone redesign the UI ? 

### ISSUE THREAD

**Issue by andrejcibik** [greymass/eos-voter#86]
Hello,
Im using the EOS voter and love the work you did. Im a UI designer so I thought to offer you my hand and maybe research some UI enhancements of your app. 

You can check out my other crypto-related work here - https://dribbble.com/shots/3987751-IOTA-wallet-concept-dark-version (not limited to IOTA :D )

Thank you :)

**Comment by aaroncox** [comment]
Perhaps soon? We are in talks with a handful of designers at the moment. I'd recommend reaching out to us at hello@greymass.com! 

Going to close this since it isn't an issue, but the conversation could also continue here if that's easiest in the short term.
