### ISSUE TITLE
Desktop file does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [greymass/eos-voter#89]
`eos-voter.desktop: error: value "0.1.5" for key "Version" in group "Desktop Entry" is not a known version`

Please use the latest version of electron-builder to see whether this fixes the problem.

https://github.com/greymass/eos-voter/blob/8f709ce4b85cfaf4eb40cd2ec6f5f5b4a64ad2ee/package.json#L155

Reference:
https://github.com/AppImage/appimage.github.io/pull/613

**Comment by aaroncox** [comment]
We removed that entry in v0.1.6 - as I don't even think we were using that field properly.
